// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_ST_fsm_state1 = "1";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv1_1 = "1";
const sc_lv<4> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv4_9 = "1001";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_20 = "100000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_3F = "111111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_40 = "1000000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_5F = "1011111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_60 = "1100000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_7F = "1111111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_80 = "10000000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_9F = "10011111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_A0 = "10100000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_BF = "10111111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_C0 = "11000000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_DF = "11011111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_E0 = "11100000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_FF = "11111111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_700 = "11100000000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_8FF = "100011111111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_400 = "10000000000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_5FF = "10111111111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_100 = "100000000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_lv32_2FF = "1011111111";
const bool cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::ap_const_boolean_1 = true;

cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    layer_in_row_Array_V_9_0_0_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_0_0_U");
    layer_in_row_Array_V_9_0_0_U->clk(ap_clk);
    layer_in_row_Array_V_9_0_0_U->reset(ap_rst);
    layer_in_row_Array_V_9_0_0_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_0_0_U->ce0(layer_in_row_Array_V_9_0_0_ce0);
    layer_in_row_Array_V_9_0_0_U->we0(layer_in_row_Array_V_9_0_0_we0);
    layer_in_row_Array_V_9_0_0_U->d0(trunc_ln203_fu_144_p1);
    layer_in_row_Array_V_9_0_0_U->q0(layer_in_row_Array_V_9_0_0_q0);
    layer_in_row_Array_V_9_1_0_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_1_0_U");
    layer_in_row_Array_V_9_1_0_U->clk(ap_clk);
    layer_in_row_Array_V_9_1_0_U->reset(ap_rst);
    layer_in_row_Array_V_9_1_0_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_1_0_U->ce0(layer_in_row_Array_V_9_1_0_ce0);
    layer_in_row_Array_V_9_1_0_U->we0(layer_in_row_Array_V_9_1_0_we0);
    layer_in_row_Array_V_9_1_0_U->d0(layer_in_row_Array_V_9_0_0_q0);
    layer_in_row_Array_V_9_1_0_U->q0(layer_in_row_Array_V_9_1_0_q0);
    layer_in_row_Array_V_9_0_1_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_0_1_U");
    layer_in_row_Array_V_9_0_1_U->clk(ap_clk);
    layer_in_row_Array_V_9_0_1_U->reset(ap_rst);
    layer_in_row_Array_V_9_0_1_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_0_1_U->ce0(layer_in_row_Array_V_9_0_1_ce0);
    layer_in_row_Array_V_9_0_1_U->we0(layer_in_row_Array_V_9_0_1_we0);
    layer_in_row_Array_V_9_0_1_U->d0(layer_in_row_Array_V_9_0_1_d0);
    layer_in_row_Array_V_9_0_1_U->q0(layer_in_row_Array_V_9_0_1_q0);
    layer_in_row_Array_V_9_1_1_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_1_1_U");
    layer_in_row_Array_V_9_1_1_U->clk(ap_clk);
    layer_in_row_Array_V_9_1_1_U->reset(ap_rst);
    layer_in_row_Array_V_9_1_1_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_1_1_U->ce0(layer_in_row_Array_V_9_1_1_ce0);
    layer_in_row_Array_V_9_1_1_U->we0(layer_in_row_Array_V_9_1_1_we0);
    layer_in_row_Array_V_9_1_1_U->d0(layer_in_row_Array_V_9_0_1_q0);
    layer_in_row_Array_V_9_1_1_U->q0(layer_in_row_Array_V_9_1_1_q0);
    layer_in_row_Array_V_9_0_2_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_0_2_U");
    layer_in_row_Array_V_9_0_2_U->clk(ap_clk);
    layer_in_row_Array_V_9_0_2_U->reset(ap_rst);
    layer_in_row_Array_V_9_0_2_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_0_2_U->ce0(layer_in_row_Array_V_9_0_2_ce0);
    layer_in_row_Array_V_9_0_2_U->we0(layer_in_row_Array_V_9_0_2_we0);
    layer_in_row_Array_V_9_0_2_U->d0(layer_in_row_Array_V_9_0_2_d0);
    layer_in_row_Array_V_9_0_2_U->q0(layer_in_row_Array_V_9_0_2_q0);
    layer_in_row_Array_V_9_1_2_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_1_2_U");
    layer_in_row_Array_V_9_1_2_U->clk(ap_clk);
    layer_in_row_Array_V_9_1_2_U->reset(ap_rst);
    layer_in_row_Array_V_9_1_2_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_1_2_U->ce0(layer_in_row_Array_V_9_1_2_ce0);
    layer_in_row_Array_V_9_1_2_U->we0(layer_in_row_Array_V_9_1_2_we0);
    layer_in_row_Array_V_9_1_2_U->d0(layer_in_row_Array_V_9_0_2_q0);
    layer_in_row_Array_V_9_1_2_U->q0(layer_in_row_Array_V_9_1_2_q0);
    layer_in_row_Array_V_9_0_3_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_0_3_U");
    layer_in_row_Array_V_9_0_3_U->clk(ap_clk);
    layer_in_row_Array_V_9_0_3_U->reset(ap_rst);
    layer_in_row_Array_V_9_0_3_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_0_3_U->ce0(layer_in_row_Array_V_9_0_3_ce0);
    layer_in_row_Array_V_9_0_3_U->we0(layer_in_row_Array_V_9_0_3_we0);
    layer_in_row_Array_V_9_0_3_U->d0(layer_in_row_Array_V_9_0_3_d0);
    layer_in_row_Array_V_9_0_3_U->q0(layer_in_row_Array_V_9_0_3_q0);
    layer_in_row_Array_V_9_1_3_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_1_3_U");
    layer_in_row_Array_V_9_1_3_U->clk(ap_clk);
    layer_in_row_Array_V_9_1_3_U->reset(ap_rst);
    layer_in_row_Array_V_9_1_3_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_1_3_U->ce0(layer_in_row_Array_V_9_1_3_ce0);
    layer_in_row_Array_V_9_1_3_U->we0(layer_in_row_Array_V_9_1_3_we0);
    layer_in_row_Array_V_9_1_3_U->d0(layer_in_row_Array_V_9_0_3_q0);
    layer_in_row_Array_V_9_1_3_U->q0(layer_in_row_Array_V_9_1_3_q0);
    layer_in_row_Array_V_9_0_4_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_0_4_U");
    layer_in_row_Array_V_9_0_4_U->clk(ap_clk);
    layer_in_row_Array_V_9_0_4_U->reset(ap_rst);
    layer_in_row_Array_V_9_0_4_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_0_4_U->ce0(layer_in_row_Array_V_9_0_4_ce0);
    layer_in_row_Array_V_9_0_4_U->we0(layer_in_row_Array_V_9_0_4_we0);
    layer_in_row_Array_V_9_0_4_U->d0(layer_in_row_Array_V_9_0_4_d0);
    layer_in_row_Array_V_9_0_4_U->q0(layer_in_row_Array_V_9_0_4_q0);
    layer_in_row_Array_V_9_1_4_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_1_4_U");
    layer_in_row_Array_V_9_1_4_U->clk(ap_clk);
    layer_in_row_Array_V_9_1_4_U->reset(ap_rst);
    layer_in_row_Array_V_9_1_4_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_1_4_U->ce0(layer_in_row_Array_V_9_1_4_ce0);
    layer_in_row_Array_V_9_1_4_U->we0(layer_in_row_Array_V_9_1_4_we0);
    layer_in_row_Array_V_9_1_4_U->d0(layer_in_row_Array_V_9_0_4_q0);
    layer_in_row_Array_V_9_1_4_U->q0(layer_in_row_Array_V_9_1_4_q0);
    layer_in_row_Array_V_9_0_5_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_0_5_U");
    layer_in_row_Array_V_9_0_5_U->clk(ap_clk);
    layer_in_row_Array_V_9_0_5_U->reset(ap_rst);
    layer_in_row_Array_V_9_0_5_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_0_5_U->ce0(layer_in_row_Array_V_9_0_5_ce0);
    layer_in_row_Array_V_9_0_5_U->we0(layer_in_row_Array_V_9_0_5_we0);
    layer_in_row_Array_V_9_0_5_U->d0(layer_in_row_Array_V_9_0_5_d0);
    layer_in_row_Array_V_9_0_5_U->q0(layer_in_row_Array_V_9_0_5_q0);
    layer_in_row_Array_V_9_1_5_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_1_5_U");
    layer_in_row_Array_V_9_1_5_U->clk(ap_clk);
    layer_in_row_Array_V_9_1_5_U->reset(ap_rst);
    layer_in_row_Array_V_9_1_5_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_1_5_U->ce0(layer_in_row_Array_V_9_1_5_ce0);
    layer_in_row_Array_V_9_1_5_U->we0(layer_in_row_Array_V_9_1_5_we0);
    layer_in_row_Array_V_9_1_5_U->d0(layer_in_row_Array_V_9_0_5_q0);
    layer_in_row_Array_V_9_1_5_U->q0(layer_in_row_Array_V_9_1_5_q0);
    layer_in_row_Array_V_9_0_6_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_0_6_U");
    layer_in_row_Array_V_9_0_6_U->clk(ap_clk);
    layer_in_row_Array_V_9_0_6_U->reset(ap_rst);
    layer_in_row_Array_V_9_0_6_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_0_6_U->ce0(layer_in_row_Array_V_9_0_6_ce0);
    layer_in_row_Array_V_9_0_6_U->we0(layer_in_row_Array_V_9_0_6_we0);
    layer_in_row_Array_V_9_0_6_U->d0(layer_in_row_Array_V_9_0_6_d0);
    layer_in_row_Array_V_9_0_6_U->q0(layer_in_row_Array_V_9_0_6_q0);
    layer_in_row_Array_V_9_1_6_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_1_6_U");
    layer_in_row_Array_V_9_1_6_U->clk(ap_clk);
    layer_in_row_Array_V_9_1_6_U->reset(ap_rst);
    layer_in_row_Array_V_9_1_6_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_1_6_U->ce0(layer_in_row_Array_V_9_1_6_ce0);
    layer_in_row_Array_V_9_1_6_U->we0(layer_in_row_Array_V_9_1_6_we0);
    layer_in_row_Array_V_9_1_6_U->d0(layer_in_row_Array_V_9_0_6_q0);
    layer_in_row_Array_V_9_1_6_U->q0(layer_in_row_Array_V_9_1_6_q0);
    layer_in_row_Array_V_9_0_7_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_0_7_U");
    layer_in_row_Array_V_9_0_7_U->clk(ap_clk);
    layer_in_row_Array_V_9_0_7_U->reset(ap_rst);
    layer_in_row_Array_V_9_0_7_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_0_7_U->ce0(layer_in_row_Array_V_9_0_7_ce0);
    layer_in_row_Array_V_9_0_7_U->we0(layer_in_row_Array_V_9_0_7_we0);
    layer_in_row_Array_V_9_0_7_U->d0(layer_in_row_Array_V_9_0_7_d0);
    layer_in_row_Array_V_9_0_7_U->q0(layer_in_row_Array_V_9_0_7_q0);
    layer_in_row_Array_V_9_1_7_U = new cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_lay8jQ("layer_in_row_Array_V_9_1_7_U");
    layer_in_row_Array_V_9_1_7_U->clk(ap_clk);
    layer_in_row_Array_V_9_1_7_U->reset(ap_rst);
    layer_in_row_Array_V_9_1_7_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_9_1_7_U->ce0(layer_in_row_Array_V_9_1_7_ce0);
    layer_in_row_Array_V_9_1_7_U->we0(layer_in_row_Array_V_9_1_7_we0);
    layer_in_row_Array_V_9_1_7_U->d0(layer_in_row_Array_V_9_0_7_q0);
    layer_in_row_Array_V_9_1_7_U->q0(layer_in_row_Array_V_9_1_7_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_read );
    sensitive << ( layer_in_row_Array_V_9_0_0_q0 );
    sensitive << ( layer_in_row_Array_V_9_1_0_q0 );
    sensitive << ( layer_in_row_Array_V_9_0_1_q0 );
    sensitive << ( layer_in_row_Array_V_9_1_1_q0 );
    sensitive << ( layer_in_row_Array_V_9_0_2_q0 );
    sensitive << ( layer_in_row_Array_V_9_1_2_q0 );
    sensitive << ( layer_in_row_Array_V_9_0_3_q0 );
    sensitive << ( layer_in_row_Array_V_9_1_3_q0 );
    sensitive << ( layer_in_row_Array_V_9_0_4_q0 );
    sensitive << ( layer_in_row_Array_V_9_1_4_q0 );
    sensitive << ( layer_in_row_Array_V_9_0_5_q0 );
    sensitive << ( layer_in_row_Array_V_9_1_5_q0 );
    sensitive << ( layer_in_row_Array_V_9_0_6_q0 );
    sensitive << ( layer_in_row_Array_V_9_1_6_q0 );
    sensitive << ( layer_in_row_Array_V_9_0_7_q0 );
    sensitive << ( layer_in_row_Array_V_9_1_7_q0 );
    sensitive << ( tmp_fu_378_p4 );
    sensitive << ( tmp_3_fu_388_p4 );
    sensitive << ( tmp_4_fu_398_p4 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_0_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_0_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_1_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_1_d0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_read );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_1_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_2_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_2_d0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_read );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_2_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_3_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_3_d0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_read );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_3_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_4_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_4_d0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_read );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_4_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_5_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_5_d0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_read );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_5_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_6_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_6_d0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_read );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_6_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_7_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_7_d0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_read );

    SC_METHOD(thread_layer_in_row_Array_V_9_0_7_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_0_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_0_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_1_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_1_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_2_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_2_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_3_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_3_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_4_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_4_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_5_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_5_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_6_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_6_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_7_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_layer_in_row_Array_V_9_1_7_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_tmp_3_fu_388_p4);
    sensitive << ( output_V_read );

    SC_METHOD(thread_tmp_4_fu_398_p4);
    sensitive << ( output_V_read );

    SC_METHOD(thread_tmp_fu_378_p4);
    sensitive << ( output_V_read );

    SC_METHOD(thread_trunc_ln203_fu_144_p1);
    sensitive << ( data_V_read );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "1";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_read, "(port)data_V_read");
    sc_trace(mVcdFile, output_V_read, "(port)output_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_0_ce0, "layer_in_row_Array_V_9_0_0_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_0_we0, "layer_in_row_Array_V_9_0_0_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_0_q0, "layer_in_row_Array_V_9_0_0_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_0_ce0, "layer_in_row_Array_V_9_1_0_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_0_we0, "layer_in_row_Array_V_9_1_0_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_0_q0, "layer_in_row_Array_V_9_1_0_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_1_ce0, "layer_in_row_Array_V_9_0_1_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_1_we0, "layer_in_row_Array_V_9_0_1_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_1_d0, "layer_in_row_Array_V_9_0_1_d0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_1_q0, "layer_in_row_Array_V_9_0_1_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_1_ce0, "layer_in_row_Array_V_9_1_1_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_1_we0, "layer_in_row_Array_V_9_1_1_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_1_q0, "layer_in_row_Array_V_9_1_1_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_2_ce0, "layer_in_row_Array_V_9_0_2_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_2_we0, "layer_in_row_Array_V_9_0_2_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_2_d0, "layer_in_row_Array_V_9_0_2_d0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_2_q0, "layer_in_row_Array_V_9_0_2_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_2_ce0, "layer_in_row_Array_V_9_1_2_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_2_we0, "layer_in_row_Array_V_9_1_2_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_2_q0, "layer_in_row_Array_V_9_1_2_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_3_ce0, "layer_in_row_Array_V_9_0_3_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_3_we0, "layer_in_row_Array_V_9_0_3_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_3_d0, "layer_in_row_Array_V_9_0_3_d0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_3_q0, "layer_in_row_Array_V_9_0_3_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_3_ce0, "layer_in_row_Array_V_9_1_3_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_3_we0, "layer_in_row_Array_V_9_1_3_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_3_q0, "layer_in_row_Array_V_9_1_3_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_4_ce0, "layer_in_row_Array_V_9_0_4_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_4_we0, "layer_in_row_Array_V_9_0_4_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_4_d0, "layer_in_row_Array_V_9_0_4_d0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_4_q0, "layer_in_row_Array_V_9_0_4_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_4_ce0, "layer_in_row_Array_V_9_1_4_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_4_we0, "layer_in_row_Array_V_9_1_4_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_4_q0, "layer_in_row_Array_V_9_1_4_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_5_ce0, "layer_in_row_Array_V_9_0_5_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_5_we0, "layer_in_row_Array_V_9_0_5_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_5_d0, "layer_in_row_Array_V_9_0_5_d0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_5_q0, "layer_in_row_Array_V_9_0_5_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_5_ce0, "layer_in_row_Array_V_9_1_5_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_5_we0, "layer_in_row_Array_V_9_1_5_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_5_q0, "layer_in_row_Array_V_9_1_5_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_6_ce0, "layer_in_row_Array_V_9_0_6_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_6_we0, "layer_in_row_Array_V_9_0_6_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_6_d0, "layer_in_row_Array_V_9_0_6_d0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_6_q0, "layer_in_row_Array_V_9_0_6_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_6_ce0, "layer_in_row_Array_V_9_1_6_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_6_we0, "layer_in_row_Array_V_9_1_6_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_6_q0, "layer_in_row_Array_V_9_1_6_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_7_ce0, "layer_in_row_Array_V_9_0_7_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_7_we0, "layer_in_row_Array_V_9_0_7_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_7_d0, "layer_in_row_Array_V_9_0_7_d0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_0_7_q0, "layer_in_row_Array_V_9_0_7_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_7_ce0, "layer_in_row_Array_V_9_1_7_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_7_we0, "layer_in_row_Array_V_9_1_7_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_9_1_7_q0, "layer_in_row_Array_V_9_1_7_q0");
    sc_trace(mVcdFile, trunc_ln203_fu_144_p1, "trunc_ln203_fu_144_p1");
    sc_trace(mVcdFile, tmp_fu_378_p4, "tmp_fu_378_p4");
    sc_trace(mVcdFile, tmp_3_fu_388_p4, "tmp_3_fu_388_p4");
    sc_trace(mVcdFile, tmp_4_fu_398_p4, "tmp_4_fu_398_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::~cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete layer_in_row_Array_V_9_0_0_U;
    delete layer_in_row_Array_V_9_1_0_U;
    delete layer_in_row_Array_V_9_0_1_U;
    delete layer_in_row_Array_V_9_1_1_U;
    delete layer_in_row_Array_V_9_0_2_U;
    delete layer_in_row_Array_V_9_1_2_U;
    delete layer_in_row_Array_V_9_0_3_U;
    delete layer_in_row_Array_V_9_1_3_U;
    delete layer_in_row_Array_V_9_0_4_U;
    delete layer_in_row_Array_V_9_1_4_U;
    delete layer_in_row_Array_V_9_0_5_U;
    delete layer_in_row_Array_V_9_1_5_U;
    delete layer_in_row_Array_V_9_0_6_U;
    delete layer_in_row_Array_V_9_1_6_U;
    delete layer_in_row_Array_V_9_0_7_U;
    delete layer_in_row_Array_V_9_1_7_U;
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv4_9;
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_ap_return() {
    ap_return = esl_concat<1792,512>(esl_concat<1760,32>(esl_concat<1728,32>(esl_concat<1696,32>(esl_concat<1664,32>(esl_concat<1632,32>(esl_concat<1600,32>(esl_concat<1568,32>(esl_concat<1536,32>(esl_concat<1024,512>(esl_concat<992,32>(esl_concat<960,32>(esl_concat<928,32>(esl_concat<896,32>(esl_concat<864,32>(esl_concat<832,32>(esl_concat<800,32>(esl_concat<768,32>(esl_concat<256,512>(data_V_read.read(), tmp_fu_378_p4.read()), layer_in_row_Array_V_9_0_7_q0.read()), layer_in_row_Array_V_9_0_6_q0.read()), layer_in_row_Array_V_9_0_5_q0.read()), layer_in_row_Array_V_9_0_4_q0.read()), layer_in_row_Array_V_9_0_3_q0.read()), layer_in_row_Array_V_9_0_2_q0.read()), layer_in_row_Array_V_9_0_1_q0.read()), layer_in_row_Array_V_9_0_0_q0.read()), tmp_3_fu_388_p4.read()), layer_in_row_Array_V_9_1_7_q0.read()), layer_in_row_Array_V_9_1_6_q0.read()), layer_in_row_Array_V_9_1_5_q0.read()), layer_in_row_Array_V_9_1_4_q0.read()), layer_in_row_Array_V_9_1_3_q0.read()), layer_in_row_Array_V_9_1_2_q0.read()), layer_in_row_Array_V_9_1_1_q0.read()), layer_in_row_Array_V_9_1_0_q0.read()), tmp_4_fu_398_p4.read());
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_0_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_0_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_0_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_0_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_0_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_1_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_1_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_1_d0() {
    layer_in_row_Array_V_9_0_1_d0 = data_V_read.read().range(63, 32);
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_1_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_1_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_2_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_2_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_2_d0() {
    layer_in_row_Array_V_9_0_2_d0 = data_V_read.read().range(95, 64);
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_2_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_2_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_2_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_3_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_3_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_3_d0() {
    layer_in_row_Array_V_9_0_3_d0 = data_V_read.read().range(127, 96);
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_3_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_3_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_3_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_4_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_4_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_4_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_4_d0() {
    layer_in_row_Array_V_9_0_4_d0 = data_V_read.read().range(159, 128);
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_4_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_4_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_4_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_5_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_5_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_5_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_5_d0() {
    layer_in_row_Array_V_9_0_5_d0 = data_V_read.read().range(191, 160);
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_5_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_5_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_5_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_6_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_6_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_6_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_6_d0() {
    layer_in_row_Array_V_9_0_6_d0 = data_V_read.read().range(223, 192);
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_6_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_6_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_6_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_7_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_7_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_7_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_7_d0() {
    layer_in_row_Array_V_9_0_7_d0 = data_V_read.read().range(255, 224);
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_0_7_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_0_7_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_0_7_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_0_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_0_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_0_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_0_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_0_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_1_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_1_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_1_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_1_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_2_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_2_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_2_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_2_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_2_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_3_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_3_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_3_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_3_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_3_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_4_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_4_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_4_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_4_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_4_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_4_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_5_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_5_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_5_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_5_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_5_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_5_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_6_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_6_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_6_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_6_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_6_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_6_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_7_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_7_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_7_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_layer_in_row_Array_V_9_1_7_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        layer_in_row_Array_V_9_1_7_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_9_1_7_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_tmp_3_fu_388_p4() {
    tmp_3_fu_388_p4 = output_V_read.read().range(1535, 1024);
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_tmp_4_fu_398_p4() {
    tmp_4_fu_398_p4 = output_V_read.read().range(767, 256);
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_tmp_fu_378_p4() {
    tmp_fu_378_p4 = output_V_read.read().range(2303, 1792);
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_trunc_ln203_fu_144_p1() {
    trunc_ln203_fu_144_p1 = data_V_read.read().range(32-1, 0);
}

void cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config48_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

