// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pooling2d_large_cl_nopad_pad_me.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pooling2d_large_cl_nopad_pad_me::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pooling2d_large_cl_nopad_pad_me::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state1 = "1";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state2 = "10";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state6 = "1000";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state7 = "10000";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_pp1_stage0 = "100000";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state11 = "1000000";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_pp2_stage0 = "10000000";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state19 = "100000000";
const bool pooling2d_large_cl_nopad_pad_me::ap_const_boolean_1 = true;
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_2 = "10";
const bool pooling2d_large_cl_nopad_pad_me::ap_const_boolean_0 = false;
const sc_lv<1> pooling2d_large_cl_nopad_pad_me::ap_const_lv1_0 = "0";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_5 = "101";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_7 = "111";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_1 = "1";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_4 = "100";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_6 = "110";
const sc_lv<1> pooling2d_large_cl_nopad_pad_me::ap_const_lv1_1 = "1";
const sc_lv<3> pooling2d_large_cl_nopad_pad_me::ap_const_lv3_0 = "000";
const sc_lv<7> pooling2d_large_cl_nopad_pad_me::ap_const_lv7_0 = "0000000";
const sc_lv<4> pooling2d_large_cl_nopad_pad_me::ap_const_lv4_0 = "0000";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_8 = "1000";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_3 = "11";
const sc_lv<3> pooling2d_large_cl_nopad_pad_me::ap_const_lv3_4 = "100";
const sc_lv<3> pooling2d_large_cl_nopad_pad_me::ap_const_lv3_1 = "1";
const sc_lv<7> pooling2d_large_cl_nopad_pad_me::ap_const_lv7_40 = "1000000";
const sc_lv<7> pooling2d_large_cl_nopad_pad_me::ap_const_lv7_1 = "1";
const sc_lv<4> pooling2d_large_cl_nopad_pad_me::ap_const_lv4_1 = "1";
const sc_lv<4> pooling2d_large_cl_nopad_pad_me::ap_const_lv4_8 = "1000";

pooling2d_large_cl_nopad_pad_me::pooling2d_large_cl_nopad_pad_me(sc_module_name name) : sc_module(name), mVcdFile(0) {
    memory1_0_V_U = new pooling2d_large_cl_nopad_pad_me_memory1_0_V("memory1_0_V_U");
    memory1_0_V_U->clk(ap_clk);
    memory1_0_V_U->reset(ap_rst);
    memory1_0_V_U->address0(memory1_0_V_address0);
    memory1_0_V_U->ce0(memory1_0_V_ce0);
    memory1_0_V_U->we0(memory1_0_V_we0);
    memory1_0_V_U->d0(reg_236);
    memory1_0_V_U->q0(memory1_0_V_q0);
    memory1_1_V_U = new pooling2d_large_cl_nopad_pad_me_memory1_0_V("memory1_1_V_U");
    memory1_1_V_U->clk(ap_clk);
    memory1_1_V_U->reset(ap_rst);
    memory1_1_V_U->address0(memory1_1_V_address0);
    memory1_1_V_U->ce0(memory1_1_V_ce0);
    memory1_1_V_U->we0(memory1_1_V_we0);
    memory1_1_V_U->d0(reg_236);
    memory1_1_V_U->q0(memory1_1_V_q0);
    memory2_V_U = new pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config6jbC("memory2_V_U");
    memory2_V_U->clk(ap_clk);
    memory2_V_U->reset(ap_rst);
    memory2_V_U->address0(memory2_V_address0);
    memory2_V_U->ce0(memory2_V_ce0);
    memory2_V_U->we0(memory2_V_we0);
    memory2_V_U->d0(reg_236);
    memory2_V_U->q0(memory2_V_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln203_5_fu_397_p2);
    sensitive << ( zext_ln500_reg_509 );
    sensitive << ( zext_ln203_14_fu_393_p1 );

    SC_METHOD(thread_add_ln203_fu_329_p2);
    sensitive << ( zext_ln480_fu_322_p1 );
    sensitive << ( zext_ln203_fu_326_p1 );

    SC_METHOD(thread_add_ln479_fu_261_p2);
    sensitive << ( indvar_flatten_reg_167 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp2_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln479_reg_453 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln479_reg_453 );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln495_reg_500 );

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln495_reg_500 );

    SC_METHOD(thread_ap_block_pp2_stage0);

    SC_METHOD(thread_ap_block_pp2_stage0_01001);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter3_reg );
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter5_reg );

    SC_METHOD(thread_ap_block_pp2_stage0_11001);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter3_reg );
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter5_reg );

    SC_METHOD(thread_ap_block_pp2_stage0_subdone);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter3_reg );
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter5_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state10_pp1_stage0_iter2);

    SC_METHOD(thread_ap_block_state12_pp2_stage0_iter0);

    SC_METHOD(thread_ap_block_state13_pp2_stage0_iter1);

    SC_METHOD(thread_ap_block_state14_pp2_stage0_iter2);

    SC_METHOD(thread_ap_block_state15_pp2_stage0_iter3);

    SC_METHOD(thread_ap_block_state16_pp2_stage0_iter4);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( icmp_ln500_reg_514_pp2_iter3_reg );

    SC_METHOD(thread_ap_block_state17_pp2_stage0_iter5);

    SC_METHOD(thread_ap_block_state18_pp2_stage0_iter6);
    sensitive << ( res_V_V_full_n );
    sensitive << ( icmp_ln500_reg_514_pp2_iter5_reg );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( icmp_ln479_reg_453 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state8_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state9_pp1_stage0_iter1);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( icmp_ln495_reg_500 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( icmp_ln479_fu_255_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state8);
    sensitive << ( icmp_ln495_fu_352_p2 );

    SC_METHOD(thread_ap_condition_pp2_exit_iter0_state12);
    sensitive << ( icmp_ln500_fu_381_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( icmp_ln477_fu_243_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_enable_pp2);
    sensitive << ( ap_idle_pp2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter2 );

    SC_METHOD(thread_ap_idle_pp2);
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( ap_enable_reg_pp2_iter3 );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( ap_enable_reg_pp2_iter5 );

    SC_METHOD(thread_ap_phi_mux_j_0_phi_fu_182_p4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln479_reg_453 );
    sensitive << ( j_0_reg_178 );
    sensitive << ( select_ln203_5_reg_467 );

    SC_METHOD(thread_ap_phi_mux_k10_0_phi_fu_228_p4);
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( icmp_ln500_reg_514 );
    sensitive << ( k10_0_reg_224 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( k_10_reg_518 );
    sensitive << ( ap_enable_reg_pp2_iter1 );

    SC_METHOD(thread_ap_phi_mux_k9_0_phi_fu_216_p4);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( icmp_ln495_reg_500 );
    sensitive << ( k9_0_reg_212 );
    sensitive << ( k_9_reg_504 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_data_V_V_blk_n);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln479_reg_453 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( icmp_ln495_reg_500 );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter3_reg );

    SC_METHOD(thread_data_V_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln479_reg_453 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln495_reg_500 );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter3_reg );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_i_fu_249_p2);
    sensitive << ( i_0_reg_156 );

    SC_METHOD(thread_icmp_ln1494_1_fu_422_p2);
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter3_reg );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( pool_2_V_reg_555 );
    sensitive << ( select_ln510_reg_561 );

    SC_METHOD(thread_icmp_ln1494_2_fu_432_p2);
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( reg_236 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter4_reg );
    sensitive << ( select_ln510_3_reg_567 );
    sensitive << ( ap_enable_reg_pp2_iter5 );

    SC_METHOD(thread_icmp_ln1494_fu_412_p2);
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter2_reg );
    sensitive << ( max_V_reg_538 );
    sensitive << ( pool_1_V_reg_544 );
    sensitive << ( ap_enable_reg_pp2_iter3 );

    SC_METHOD(thread_icmp_ln477_fu_243_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_156 );

    SC_METHOD(thread_icmp_ln479_fu_255_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten_reg_167 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln480_fu_273_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( k_0_reg_189 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln479_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln494_fu_340_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( j8_0_reg_200 );

    SC_METHOD(thread_icmp_ln495_fu_352_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_phi_mux_k9_0_phi_fu_216_p4 );

    SC_METHOD(thread_icmp_ln500_fu_381_p2);
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( ap_phi_mux_k10_0_phi_fu_228_p4 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( icmp_ln477_fu_243_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_j_27_fu_346_p2);
    sensitive << ( j8_0_reg_200 );

    SC_METHOD(thread_j_fu_267_p2);
    sensitive << ( ap_phi_mux_j_0_phi_fu_182_p4 );

    SC_METHOD(thread_k_10_fu_387_p2);
    sensitive << ( ap_phi_mux_k10_0_phi_fu_228_p4 );

    SC_METHOD(thread_k_9_fu_358_p2);
    sensitive << ( ap_phi_mux_k9_0_phi_fu_216_p4 );

    SC_METHOD(thread_k_fu_309_p2);
    sensitive << ( select_ln203_fu_279_p3 );

    SC_METHOD(thread_memory1_0_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( zext_ln203_13_fu_335_p1 );
    sensitive << ( zext_ln203_15_fu_402_p1 );

    SC_METHOD(thread_memory1_0_V_ce0);
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp2_iter1 );

    SC_METHOD(thread_memory1_0_V_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( trunc_ln203_reg_472_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_memory1_1_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( zext_ln203_13_fu_335_p1 );
    sensitive << ( zext_ln203_15_fu_402_p1 );

    SC_METHOD(thread_memory1_1_V_ce0);
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp2_iter1 );

    SC_METHOD(thread_memory1_1_V_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( trunc_ln203_reg_472_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_memory2_V_address0);
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( zext_ln498_fu_364_p1 );
    sensitive << ( zext_ln502_fu_407_p1 );

    SC_METHOD(thread_memory2_V_ce0);
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( ap_enable_reg_pp1_iter2 );

    SC_METHOD(thread_memory2_V_we0);
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( icmp_ln495_reg_500_pp1_iter1_reg );
    sensitive << ( ap_enable_reg_pp1_iter2 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_res_V_V_blk_n);
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter5_reg );

    SC_METHOD(thread_res_V_V_din);
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter5_reg );
    sensitive << ( tmp_V_reg_573 );
    sensitive << ( ap_block_pp2_stage0_01001 );

    SC_METHOD(thread_res_V_V_write);
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln500_reg_514_pp2_iter5_reg );
    sensitive << ( ap_block_pp2_stage0_11001 );

    SC_METHOD(thread_select_ln203_5_fu_287_p3);
    sensitive << ( ap_phi_mux_j_0_phi_fu_182_p4 );
    sensitive << ( icmp_ln480_fu_273_p2 );
    sensitive << ( j_fu_267_p2 );

    SC_METHOD(thread_select_ln203_fu_279_p3);
    sensitive << ( k_0_reg_189 );
    sensitive << ( icmp_ln480_fu_273_p2 );

    SC_METHOD(thread_select_ln510_3_fu_426_p3);
    sensitive << ( pool_2_V_reg_555 );
    sensitive << ( select_ln510_reg_561 );
    sensitive << ( icmp_ln1494_1_fu_422_p2 );

    SC_METHOD(thread_select_ln510_fu_416_p3);
    sensitive << ( max_V_reg_538 );
    sensitive << ( pool_1_V_reg_544 );
    sensitive << ( icmp_ln1494_fu_412_p2 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_1_fu_369_p3);
    sensitive << ( j8_0_reg_200 );

    SC_METHOD(thread_tmp_9_fu_315_p3);
    sensitive << ( zext_ln203_mid2_v_reg_476 );

    SC_METHOD(thread_tmp_V_fu_437_p3);
    sensitive << ( reg_236 );
    sensitive << ( select_ln510_3_reg_567 );
    sensitive << ( icmp_ln1494_2_fu_432_p2 );

    SC_METHOD(thread_trunc_ln203_fu_295_p1);
    sensitive << ( select_ln203_5_fu_287_p3 );

    SC_METHOD(thread_zext_ln203_13_fu_335_p1);
    sensitive << ( add_ln203_reg_486 );

    SC_METHOD(thread_zext_ln203_14_fu_393_p1);
    sensitive << ( ap_phi_mux_k10_0_phi_fu_228_p4 );

    SC_METHOD(thread_zext_ln203_15_fu_402_p1);
    sensitive << ( add_ln203_5_reg_523 );

    SC_METHOD(thread_zext_ln203_fu_326_p1);
    sensitive << ( select_ln203_reg_462 );

    SC_METHOD(thread_zext_ln480_fu_322_p1);
    sensitive << ( tmp_9_fu_315_p3 );

    SC_METHOD(thread_zext_ln498_fu_364_p1);
    sensitive << ( k9_0_reg_212_pp1_iter1_reg );

    SC_METHOD(thread_zext_ln500_fu_377_p1);
    sensitive << ( tmp_1_fu_369_p3 );

    SC_METHOD(thread_zext_ln502_fu_407_p1);
    sensitive << ( k10_0_reg_224_pp2_iter1_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln477_fu_243_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln479_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln494_fu_340_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln495_fu_352_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( icmp_ln500_fu_381_p2 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_block_pp2_stage0_subdone );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( ap_enable_reg_pp2_iter5 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter5 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pooling2d_large_cl_nopad_pad_me_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, data_V_V_dout, "(port)data_V_V_dout");
    sc_trace(mVcdFile, data_V_V_empty_n, "(port)data_V_V_empty_n");
    sc_trace(mVcdFile, data_V_V_read, "(port)data_V_V_read");
    sc_trace(mVcdFile, res_V_V_din, "(port)res_V_V_din");
    sc_trace(mVcdFile, res_V_V_full_n, "(port)res_V_V_full_n");
    sc_trace(mVcdFile, res_V_V_write, "(port)res_V_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, data_V_V_blk_n, "data_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln479_reg_453, "icmp_ln479_reg_453");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, icmp_ln495_reg_500, "icmp_ln495_reg_500");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter4, "ap_enable_reg_pp2_iter4");
    sc_trace(mVcdFile, ap_block_pp2_stage0, "ap_block_pp2_stage0");
    sc_trace(mVcdFile, icmp_ln500_reg_514, "icmp_ln500_reg_514");
    sc_trace(mVcdFile, icmp_ln500_reg_514_pp2_iter3_reg, "icmp_ln500_reg_514_pp2_iter3_reg");
    sc_trace(mVcdFile, res_V_V_blk_n, "res_V_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter6, "ap_enable_reg_pp2_iter6");
    sc_trace(mVcdFile, icmp_ln500_reg_514_pp2_iter5_reg, "icmp_ln500_reg_514_pp2_iter5_reg");
    sc_trace(mVcdFile, indvar_flatten_reg_167, "indvar_flatten_reg_167");
    sc_trace(mVcdFile, j_0_reg_178, "j_0_reg_178");
    sc_trace(mVcdFile, k_0_reg_189, "k_0_reg_189");
    sc_trace(mVcdFile, k9_0_reg_212, "k9_0_reg_212");
    sc_trace(mVcdFile, k9_0_reg_212_pp1_iter1_reg, "k9_0_reg_212_pp1_iter1_reg");
    sc_trace(mVcdFile, ap_block_state8_pp1_stage0_iter0, "ap_block_state8_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state9_pp1_stage0_iter1, "ap_block_state9_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state10_pp1_stage0_iter2, "ap_block_state10_pp1_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, k10_0_reg_224, "k10_0_reg_224");
    sc_trace(mVcdFile, k10_0_reg_224_pp2_iter1_reg, "k10_0_reg_224_pp2_iter1_reg");
    sc_trace(mVcdFile, ap_CS_fsm_pp2_stage0, "ap_CS_fsm_pp2_stage0");
    sc_trace(mVcdFile, ap_block_state12_pp2_stage0_iter0, "ap_block_state12_pp2_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state13_pp2_stage0_iter1, "ap_block_state13_pp2_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state14_pp2_stage0_iter2, "ap_block_state14_pp2_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state15_pp2_stage0_iter3, "ap_block_state15_pp2_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state16_pp2_stage0_iter4, "ap_block_state16_pp2_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state17_pp2_stage0_iter5, "ap_block_state17_pp2_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state18_pp2_stage0_iter6, "ap_block_state18_pp2_stage0_iter6");
    sc_trace(mVcdFile, ap_block_pp2_stage0_11001, "ap_block_pp2_stage0_11001");
    sc_trace(mVcdFile, reg_236, "reg_236");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln477_fu_243_p2, "icmp_ln477_fu_243_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_249_p2, "i_fu_249_p2");
    sc_trace(mVcdFile, i_reg_448, "i_reg_448");
    sc_trace(mVcdFile, icmp_ln479_fu_255_p2, "icmp_ln479_fu_255_p2");
    sc_trace(mVcdFile, add_ln479_fu_261_p2, "add_ln479_fu_261_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, select_ln203_fu_279_p3, "select_ln203_fu_279_p3");
    sc_trace(mVcdFile, select_ln203_reg_462, "select_ln203_reg_462");
    sc_trace(mVcdFile, select_ln203_5_fu_287_p3, "select_ln203_5_fu_287_p3");
    sc_trace(mVcdFile, select_ln203_5_reg_467, "select_ln203_5_reg_467");
    sc_trace(mVcdFile, trunc_ln203_fu_295_p1, "trunc_ln203_fu_295_p1");
    sc_trace(mVcdFile, trunc_ln203_reg_472, "trunc_ln203_reg_472");
    sc_trace(mVcdFile, trunc_ln203_reg_472_pp0_iter1_reg, "trunc_ln203_reg_472_pp0_iter1_reg");
    sc_trace(mVcdFile, zext_ln203_mid2_v_reg_476, "zext_ln203_mid2_v_reg_476");
    sc_trace(mVcdFile, k_fu_309_p2, "k_fu_309_p2");
    sc_trace(mVcdFile, add_ln203_fu_329_p2, "add_ln203_fu_329_p2");
    sc_trace(mVcdFile, add_ln203_reg_486, "add_ln203_reg_486");
    sc_trace(mVcdFile, icmp_ln494_fu_340_p2, "icmp_ln494_fu_340_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, j_27_fu_346_p2, "j_27_fu_346_p2");
    sc_trace(mVcdFile, j_27_reg_495, "j_27_reg_495");
    sc_trace(mVcdFile, icmp_ln495_fu_352_p2, "icmp_ln495_fu_352_p2");
    sc_trace(mVcdFile, icmp_ln495_reg_500_pp1_iter1_reg, "icmp_ln495_reg_500_pp1_iter1_reg");
    sc_trace(mVcdFile, k_9_fu_358_p2, "k_9_fu_358_p2");
    sc_trace(mVcdFile, k_9_reg_504, "k_9_reg_504");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, zext_ln500_fu_377_p1, "zext_ln500_fu_377_p1");
    sc_trace(mVcdFile, zext_ln500_reg_509, "zext_ln500_reg_509");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, icmp_ln500_fu_381_p2, "icmp_ln500_fu_381_p2");
    sc_trace(mVcdFile, icmp_ln500_reg_514_pp2_iter1_reg, "icmp_ln500_reg_514_pp2_iter1_reg");
    sc_trace(mVcdFile, icmp_ln500_reg_514_pp2_iter2_reg, "icmp_ln500_reg_514_pp2_iter2_reg");
    sc_trace(mVcdFile, icmp_ln500_reg_514_pp2_iter4_reg, "icmp_ln500_reg_514_pp2_iter4_reg");
    sc_trace(mVcdFile, k_10_fu_387_p2, "k_10_fu_387_p2");
    sc_trace(mVcdFile, k_10_reg_518, "k_10_reg_518");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter0, "ap_enable_reg_pp2_iter0");
    sc_trace(mVcdFile, add_ln203_5_fu_397_p2, "add_ln203_5_fu_397_p2");
    sc_trace(mVcdFile, add_ln203_5_reg_523, "add_ln203_5_reg_523");
    sc_trace(mVcdFile, memory1_0_V_q0, "memory1_0_V_q0");
    sc_trace(mVcdFile, max_V_reg_538, "max_V_reg_538");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter2, "ap_enable_reg_pp2_iter2");
    sc_trace(mVcdFile, memory1_1_V_q0, "memory1_1_V_q0");
    sc_trace(mVcdFile, pool_1_V_reg_544, "pool_1_V_reg_544");
    sc_trace(mVcdFile, memory2_V_q0, "memory2_V_q0");
    sc_trace(mVcdFile, pool_2_V_reg_555, "pool_2_V_reg_555");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter3, "ap_enable_reg_pp2_iter3");
    sc_trace(mVcdFile, select_ln510_fu_416_p3, "select_ln510_fu_416_p3");
    sc_trace(mVcdFile, select_ln510_reg_561, "select_ln510_reg_561");
    sc_trace(mVcdFile, select_ln510_3_fu_426_p3, "select_ln510_3_fu_426_p3");
    sc_trace(mVcdFile, select_ln510_3_reg_567, "select_ln510_3_reg_567");
    sc_trace(mVcdFile, tmp_V_fu_437_p3, "tmp_V_fu_437_p3");
    sc_trace(mVcdFile, tmp_V_reg_573, "tmp_V_reg_573");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state8, "ap_condition_pp1_exit_iter0_state8");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter2, "ap_enable_reg_pp1_iter2");
    sc_trace(mVcdFile, ap_block_pp2_stage0_subdone, "ap_block_pp2_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp2_exit_iter0_state12, "ap_condition_pp2_exit_iter0_state12");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter1, "ap_enable_reg_pp2_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter5, "ap_enable_reg_pp2_iter5");
    sc_trace(mVcdFile, memory1_0_V_address0, "memory1_0_V_address0");
    sc_trace(mVcdFile, memory1_0_V_ce0, "memory1_0_V_ce0");
    sc_trace(mVcdFile, memory1_0_V_we0, "memory1_0_V_we0");
    sc_trace(mVcdFile, memory1_1_V_address0, "memory1_1_V_address0");
    sc_trace(mVcdFile, memory1_1_V_ce0, "memory1_1_V_ce0");
    sc_trace(mVcdFile, memory1_1_V_we0, "memory1_1_V_we0");
    sc_trace(mVcdFile, memory2_V_address0, "memory2_V_address0");
    sc_trace(mVcdFile, memory2_V_ce0, "memory2_V_ce0");
    sc_trace(mVcdFile, memory2_V_we0, "memory2_V_we0");
    sc_trace(mVcdFile, i_0_reg_156, "i_0_reg_156");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_phi_mux_j_0_phi_fu_182_p4, "ap_phi_mux_j_0_phi_fu_182_p4");
    sc_trace(mVcdFile, j8_0_reg_200, "j8_0_reg_200");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_phi_mux_k9_0_phi_fu_216_p4, "ap_phi_mux_k9_0_phi_fu_216_p4");
    sc_trace(mVcdFile, ap_phi_mux_k10_0_phi_fu_228_p4, "ap_phi_mux_k10_0_phi_fu_228_p4");
    sc_trace(mVcdFile, zext_ln203_13_fu_335_p1, "zext_ln203_13_fu_335_p1");
    sc_trace(mVcdFile, zext_ln498_fu_364_p1, "zext_ln498_fu_364_p1");
    sc_trace(mVcdFile, zext_ln203_15_fu_402_p1, "zext_ln203_15_fu_402_p1");
    sc_trace(mVcdFile, zext_ln502_fu_407_p1, "zext_ln502_fu_407_p1");
    sc_trace(mVcdFile, ap_block_pp2_stage0_01001, "ap_block_pp2_stage0_01001");
    sc_trace(mVcdFile, icmp_ln480_fu_273_p2, "icmp_ln480_fu_273_p2");
    sc_trace(mVcdFile, j_fu_267_p2, "j_fu_267_p2");
    sc_trace(mVcdFile, tmp_9_fu_315_p3, "tmp_9_fu_315_p3");
    sc_trace(mVcdFile, zext_ln480_fu_322_p1, "zext_ln480_fu_322_p1");
    sc_trace(mVcdFile, zext_ln203_fu_326_p1, "zext_ln203_fu_326_p1");
    sc_trace(mVcdFile, tmp_1_fu_369_p3, "tmp_1_fu_369_p3");
    sc_trace(mVcdFile, zext_ln203_14_fu_393_p1, "zext_ln203_14_fu_393_p1");
    sc_trace(mVcdFile, icmp_ln1494_fu_412_p2, "icmp_ln1494_fu_412_p2");
    sc_trace(mVcdFile, icmp_ln1494_1_fu_422_p2, "icmp_ln1494_1_fu_422_p2");
    sc_trace(mVcdFile, icmp_ln1494_2_fu_432_p2, "icmp_ln1494_2_fu_432_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
    sc_trace(mVcdFile, ap_idle_pp2, "ap_idle_pp2");
    sc_trace(mVcdFile, ap_enable_pp2, "ap_enable_pp2");
#endif

    }
}

pooling2d_large_cl_nopad_pad_me::~pooling2d_large_cl_nopad_pad_me() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete memory1_0_V_U;
    delete memory1_1_V_U;
    delete memory2_V_U;
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(icmp_ln477_fu_243_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln477_fu_243_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln477_fu_243_p2.read()))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state8.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln494_fu_340_p2.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state8.read())) {
                ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state8.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter2 = ap_enable_reg_pp1_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln494_fu_340_p2.read()))) {
            ap_enable_reg_pp1_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp2_exit_iter0_state12.read()))) {
            ap_enable_reg_pp2_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
            ap_enable_reg_pp2_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp2_exit_iter0_state12.read())) {
                ap_enable_reg_pp2_iter1 = (ap_condition_pp2_exit_iter0_state12.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp2_iter1 = ap_enable_reg_pp2_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter2 = ap_enable_reg_pp2_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter3 = ap_enable_reg_pp2_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter4 = ap_enable_reg_pp2_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter5 = ap_enable_reg_pp2_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter6 = ap_enable_reg_pp2_iter5.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
            ap_enable_reg_pp2_iter6 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(icmp_ln494_fu_340_p2.read(), ap_const_lv1_1))) {
        i_0_reg_156 = i_reg_448.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_0_reg_156 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln477_fu_243_p2.read()))) {
        indvar_flatten_reg_167 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln479_fu_255_p2.read()))) {
        indvar_flatten_reg_167 = add_ln479_fu_261_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j8_0_reg_200 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        j8_0_reg_200 = j_27_reg_495.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln477_fu_243_p2.read()))) {
        j_0_reg_178 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(icmp_ln479_reg_453.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        j_0_reg_178 = select_ln203_5_reg_467.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        k10_0_reg_224 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        k10_0_reg_224 = k_10_reg_518.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln494_fu_340_p2.read()))) {
        k9_0_reg_212 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_500.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        k9_0_reg_212 = k_9_reg_504.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln477_fu_243_p2.read()))) {
        k_0_reg_189 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln479_fu_255_p2.read()))) {
        k_0_reg_189 = k_fu_309_p2.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_fu_381_p2.read()))) {
        add_ln203_5_reg_523 = add_ln203_5_fu_397_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(icmp_ln479_reg_453.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        add_ln203_reg_486 = add_ln203_fu_329_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_448 = i_fu_249_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln479_reg_453 = icmp_ln479_fu_255_p2.read();
        trunc_ln203_reg_472_pp0_iter1_reg = trunc_ln203_reg_472.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln495_reg_500 = icmp_ln495_fu_352_p2.read();
        icmp_ln495_reg_500_pp1_iter1_reg = icmp_ln495_reg_500.read();
        k9_0_reg_212_pp1_iter1_reg = k9_0_reg_212.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln500_reg_514 = icmp_ln500_fu_381_p2.read();
        icmp_ln500_reg_514_pp2_iter1_reg = icmp_ln500_reg_514.read();
        k10_0_reg_224_pp2_iter1_reg = k10_0_reg_224.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln500_reg_514_pp2_iter2_reg = icmp_ln500_reg_514_pp2_iter1_reg.read();
        icmp_ln500_reg_514_pp2_iter3_reg = icmp_ln500_reg_514_pp2_iter2_reg.read();
        icmp_ln500_reg_514_pp2_iter4_reg = icmp_ln500_reg_514_pp2_iter3_reg.read();
        icmp_ln500_reg_514_pp2_iter5_reg = icmp_ln500_reg_514_pp2_iter4_reg.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        j_27_reg_495 = j_27_fu_346_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()))) {
        k_10_reg_518 = k_10_fu_387_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        k_9_reg_504 = k_9_fu_358_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter1_reg.read()))) {
        max_V_reg_538 = memory1_0_V_q0.read();
        pool_1_V_reg_544 = memory1_1_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter2_reg.read()))) {
        pool_2_V_reg_555 = memory2_V_q0.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln479_reg_453.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_500.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0)))) {
        reg_236 = data_V_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln479_fu_255_p2.read()))) {
        select_ln203_5_reg_467 = select_ln203_5_fu_287_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln479_fu_255_p2.read()))) {
        select_ln203_reg_462 = select_ln203_fu_279_p3.read();
        trunc_ln203_reg_472 = trunc_ln203_fu_295_p1.read();
        zext_ln203_mid2_v_reg_476 = select_ln203_5_fu_287_p3.read().range(3, 1);
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter3_reg.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0))) {
        select_ln510_3_reg_567 = select_ln510_3_fu_426_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter2_reg.read()))) {
        select_ln510_reg_561 = select_ln510_fu_416_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter4_reg.read()))) {
        tmp_V_reg_573 = tmp_V_fu_437_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        zext_ln500_reg_509 = zext_ln500_fu_377_p1.read();
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_add_ln203_5_fu_397_p2() {
    add_ln203_5_fu_397_p2 = (!zext_ln500_reg_509.read().is_01() || !zext_ln203_14_fu_393_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln500_reg_509.read()) + sc_biguint<7>(zext_ln203_14_fu_393_p1.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_add_ln203_fu_329_p2() {
    add_ln203_fu_329_p2 = (!zext_ln480_fu_322_p1.read().is_01() || !zext_ln203_fu_326_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln480_fu_322_p1.read()) + sc_biguint<7>(zext_ln203_fu_326_p1.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_add_ln479_fu_261_p2() {
    add_ln479_fu_261_p2 = (!indvar_flatten_reg_167.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvar_flatten_reg_167.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[5];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_pp2_stage0() {
    ap_CS_fsm_pp2_stage0 = ap_CS_fsm.read()[7];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[6];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[8];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[3];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[4];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(icmp_ln479_reg_453.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(icmp_ln479_reg_453.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_500.read()) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_500.read()) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_pp2_stage0() {
    ap_block_pp2_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_pp2_stage0_01001() {
    ap_block_pp2_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter5_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read())));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_pp2_stage0_11001() {
    ap_block_pp2_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter5_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read())));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_pp2_stage0_subdone() {
    ap_block_pp2_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter5_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read())));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state10_pp1_stage0_iter2() {
    ap_block_state10_pp1_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state12_pp2_stage0_iter0() {
    ap_block_state12_pp2_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state13_pp2_stage0_iter1() {
    ap_block_state13_pp2_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state14_pp2_stage0_iter2() {
    ap_block_state14_pp2_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state15_pp2_stage0_iter3() {
    ap_block_state15_pp2_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state16_pp2_stage0_iter4() {
    ap_block_state16_pp2_stage0_iter4 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter3_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state17_pp2_stage0_iter5() {
    ap_block_state17_pp2_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state18_pp2_stage0_iter6() {
    ap_block_state18_pp2_stage0_iter6 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter5_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(icmp_ln479_reg_453.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state8_pp1_stage0_iter0() {
    ap_block_state8_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state9_pp1_stage0_iter1() {
    ap_block_state9_pp1_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_500.read()) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(icmp_ln479_fu_255_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_condition_pp1_exit_iter0_state8() {
    if (esl_seteq<1,1,1>(icmp_ln495_fu_352_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp1_exit_iter0_state8 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state8 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_condition_pp2_exit_iter0_state12() {
    if (esl_seteq<1,1,1>(icmp_ln500_fu_381_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp2_exit_iter0_state12 = ap_const_logic_1;
    } else {
        ap_condition_pp2_exit_iter0_state12 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln477_fu_243_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_enable_pp2() {
    ap_enable_pp2 = (ap_idle_pp2.read() ^ ap_const_logic_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter2.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_idle_pp2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter6.read()))) {
        ap_idle_pp2 = ap_const_logic_1;
    } else {
        ap_idle_pp2 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_phi_mux_j_0_phi_fu_182_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln479_reg_453.read(), ap_const_lv1_0))) {
        ap_phi_mux_j_0_phi_fu_182_p4 = select_ln203_5_reg_467.read();
    } else {
        ap_phi_mux_j_0_phi_fu_182_p4 = j_0_reg_178.read();
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_phi_mux_k10_0_phi_fu_228_p4() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        ap_phi_mux_k10_0_phi_fu_228_p4 = k_10_reg_518.read();
    } else {
        ap_phi_mux_k10_0_phi_fu_228_p4 = k10_0_reg_224.read();
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_phi_mux_k9_0_phi_fu_216_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_500.read()))) {
        ap_phi_mux_k9_0_phi_fu_216_p4 = k_9_reg_504.read();
    } else {
        ap_phi_mux_k9_0_phi_fu_216_p4 = k9_0_reg_212.read();
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void pooling2d_large_cl_nopad_pad_me::thread_data_V_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln479_reg_453.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_500.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter3_reg.read())))) {
        data_V_V_blk_n = data_V_V_empty_n.read();
    } else {
        data_V_V_blk_n = ap_const_logic_1;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_data_V_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(icmp_ln479_reg_453.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_500.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter3_reg.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0)))) {
        data_V_V_read = ap_const_logic_1;
    } else {
        data_V_V_read = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_i_fu_249_p2() {
    i_fu_249_p2 = (!i_0_reg_156.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_0_reg_156.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln1494_1_fu_422_p2() {
    icmp_ln1494_1_fu_422_p2 = (!pool_2_V_reg_555.read().is_01() || !select_ln510_reg_561.read().is_01())? sc_lv<1>(): (sc_bigint<32>(pool_2_V_reg_555.read()) > sc_bigint<32>(select_ln510_reg_561.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln1494_2_fu_432_p2() {
    icmp_ln1494_2_fu_432_p2 = (!reg_236.read().is_01() || !select_ln510_3_reg_567.read().is_01())? sc_lv<1>(): (sc_bigint<32>(reg_236.read()) > sc_bigint<32>(select_ln510_3_reg_567.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln1494_fu_412_p2() {
    icmp_ln1494_fu_412_p2 = (!pool_1_V_reg_544.read().is_01() || !max_V_reg_538.read().is_01())? sc_lv<1>(): (sc_bigint<32>(pool_1_V_reg_544.read()) > sc_bigint<32>(max_V_reg_538.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln477_fu_243_p2() {
    icmp_ln477_fu_243_p2 = (!i_0_reg_156.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_156.read() == ap_const_lv3_4);
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln479_fu_255_p2() {
    icmp_ln479_fu_255_p2 = (!indvar_flatten_reg_167.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_167.read() == ap_const_lv7_40);
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln480_fu_273_p2() {
    icmp_ln480_fu_273_p2 = (!k_0_reg_189.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_189.read() == ap_const_lv4_8);
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln494_fu_340_p2() {
    icmp_ln494_fu_340_p2 = (!j8_0_reg_200.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(j8_0_reg_200.read() == ap_const_lv3_4);
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln495_fu_352_p2() {
    icmp_ln495_fu_352_p2 = (!ap_phi_mux_k9_0_phi_fu_216_p4.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_k9_0_phi_fu_216_p4.read() == ap_const_lv4_8);
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln500_fu_381_p2() {
    icmp_ln500_fu_381_p2 = (!ap_phi_mux_k10_0_phi_fu_228_p4.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_k10_0_phi_fu_228_p4.read() == ap_const_lv4_8);
}

void pooling2d_large_cl_nopad_pad_me::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln477_fu_243_p2.read(), ap_const_lv1_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_j_27_fu_346_p2() {
    j_27_fu_346_p2 = (!j8_0_reg_200.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(j8_0_reg_200.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_j_fu_267_p2() {
    j_fu_267_p2 = (!ap_const_lv4_1.is_01() || !ap_phi_mux_j_0_phi_fu_182_p4.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(ap_phi_mux_j_0_phi_fu_182_p4.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_k_10_fu_387_p2() {
    k_10_fu_387_p2 = (!ap_phi_mux_k10_0_phi_fu_228_p4.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(ap_phi_mux_k10_0_phi_fu_228_p4.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_k_9_fu_358_p2() {
    k_9_fu_358_p2 = (!ap_phi_mux_k9_0_phi_fu_216_p4.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(ap_phi_mux_k9_0_phi_fu_216_p4.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_k_fu_309_p2() {
    k_fu_309_p2 = (!select_ln203_fu_279_p3.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(select_ln203_fu_279_p3.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_memory1_0_V_address0() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        memory1_0_V_address0 =  (sc_lv<5>) (zext_ln203_15_fu_402_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        memory1_0_V_address0 =  (sc_lv<5>) (zext_ln203_13_fu_335_p1.read());
    } else {
        memory1_0_V_address0 = "XXXXX";
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_memory1_0_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())))) {
        memory1_0_V_ce0 = ap_const_logic_1;
    } else {
        memory1_0_V_ce0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_memory1_0_V_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln203_reg_472_pp0_iter1_reg.read()))) {
        memory1_0_V_we0 = ap_const_logic_1;
    } else {
        memory1_0_V_we0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_memory1_1_V_address0() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        memory1_1_V_address0 =  (sc_lv<5>) (zext_ln203_15_fu_402_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        memory1_1_V_address0 =  (sc_lv<5>) (zext_ln203_13_fu_335_p1.read());
    } else {
        memory1_1_V_address0 = "XXXXX";
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_memory1_1_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())))) {
        memory1_1_V_ce0 = ap_const_logic_1;
    } else {
        memory1_1_V_ce0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_memory1_1_V_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(trunc_ln203_reg_472_pp0_iter1_reg.read(), ap_const_lv1_1))) {
        memory1_1_V_we0 = ap_const_logic_1;
    } else {
        memory1_1_V_we0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_memory2_V_address0() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()))) {
        memory2_V_address0 =  (sc_lv<3>) (zext_ln502_fu_407_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()))) {
        memory2_V_address0 =  (sc_lv<3>) (zext_ln498_fu_364_p1.read());
    } else {
        memory2_V_address0 =  (sc_lv<3>) ("XXX");
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_memory2_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read())))) {
        memory2_V_ce0 = ap_const_logic_1;
    } else {
        memory2_V_ce0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_memory2_V_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_500_pp1_iter1_reg.read()))) {
        memory2_V_we0 = ap_const_logic_1;
    } else {
        memory2_V_we0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_res_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter5_reg.read()))) {
        res_V_V_blk_n = res_V_V_full_n.read();
    } else {
        res_V_V_blk_n = ap_const_logic_1;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_res_V_V_din() {
    res_V_V_din = tmp_V_reg_573.read();
}

void pooling2d_large_cl_nopad_pad_me::thread_res_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_514_pp2_iter5_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_V_write = ap_const_logic_1;
    } else {
        res_V_V_write = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_select_ln203_5_fu_287_p3() {
    select_ln203_5_fu_287_p3 = (!icmp_ln480_fu_273_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln480_fu_273_p2.read()[0].to_bool())? j_fu_267_p2.read(): ap_phi_mux_j_0_phi_fu_182_p4.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_select_ln203_fu_279_p3() {
    select_ln203_fu_279_p3 = (!icmp_ln480_fu_273_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln480_fu_273_p2.read()[0].to_bool())? ap_const_lv4_0: k_0_reg_189.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_select_ln510_3_fu_426_p3() {
    select_ln510_3_fu_426_p3 = (!icmp_ln1494_1_fu_422_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln1494_1_fu_422_p2.read()[0].to_bool())? pool_2_V_reg_555.read(): select_ln510_reg_561.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_select_ln510_fu_416_p3() {
    select_ln510_fu_416_p3 = (!icmp_ln1494_fu_412_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln1494_fu_412_p2.read()[0].to_bool())? pool_1_V_reg_544.read(): max_V_reg_538.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_start_out() {
    start_out = real_start.read();
}

void pooling2d_large_cl_nopad_pad_me::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_tmp_1_fu_369_p3() {
    tmp_1_fu_369_p3 = esl_concat<3,3>(j8_0_reg_200.read(), ap_const_lv3_0);
}

void pooling2d_large_cl_nopad_pad_me::thread_tmp_9_fu_315_p3() {
    tmp_9_fu_315_p3 = esl_concat<3,3>(zext_ln203_mid2_v_reg_476.read(), ap_const_lv3_0);
}

void pooling2d_large_cl_nopad_pad_me::thread_tmp_V_fu_437_p3() {
    tmp_V_fu_437_p3 = (!icmp_ln1494_2_fu_432_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln1494_2_fu_432_p2.read()[0].to_bool())? reg_236.read(): select_ln510_3_reg_567.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_trunc_ln203_fu_295_p1() {
    trunc_ln203_fu_295_p1 = select_ln203_5_fu_287_p3.read().range(1-1, 0);
}

void pooling2d_large_cl_nopad_pad_me::thread_zext_ln203_13_fu_335_p1() {
    zext_ln203_13_fu_335_p1 = esl_zext<64,7>(add_ln203_reg_486.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_zext_ln203_14_fu_393_p1() {
    zext_ln203_14_fu_393_p1 = esl_zext<7,4>(ap_phi_mux_k10_0_phi_fu_228_p4.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_zext_ln203_15_fu_402_p1() {
    zext_ln203_15_fu_402_p1 = esl_zext<64,7>(add_ln203_5_reg_523.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_zext_ln203_fu_326_p1() {
    zext_ln203_fu_326_p1 = esl_zext<7,4>(select_ln203_reg_462.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_zext_ln480_fu_322_p1() {
    zext_ln480_fu_322_p1 = esl_zext<7,6>(tmp_9_fu_315_p3.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_zext_ln498_fu_364_p1() {
    zext_ln498_fu_364_p1 = esl_zext<64,4>(k9_0_reg_212_pp1_iter1_reg.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_zext_ln500_fu_377_p1() {
    zext_ln500_fu_377_p1 = esl_zext<7,6>(tmp_1_fu_369_p3.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_zext_ln502_fu_407_p1() {
    zext_ln502_fu_407_p1 = esl_zext<64,4>(k10_0_reg_224_pp2_iter1_reg.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln477_fu_243_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln479_fu_255_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln479_fu_255_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln494_fu_340_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 32 : 
            if ((!(esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln495_fu_352_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if (((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln495_fu_352_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            break;
        case 128 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp2_iter5.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln500_fu_381_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp2_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && 
  esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp2_iter5.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln500_fu_381_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp2_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

