// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pooling2d_large_cl_nopad_pad_me_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pooling2d_large_cl_nopad_pad_me_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pooling2d_large_cl_nopad_pad_me_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> pooling2d_large_cl_nopad_pad_me_1::ap_ST_fsm_state1 = "1";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me_1::ap_ST_fsm_state2 = "10";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me_1::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me_1::ap_ST_fsm_state6 = "1000";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me_1::ap_ST_fsm_state7 = "10000";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me_1::ap_ST_fsm_pp1_stage0 = "100000";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me_1::ap_ST_fsm_state11 = "1000000";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me_1::ap_ST_fsm_pp2_stage0 = "10000000";
const sc_lv<9> pooling2d_large_cl_nopad_pad_me_1::ap_ST_fsm_state19 = "100000000";
const bool pooling2d_large_cl_nopad_pad_me_1::ap_const_boolean_1 = true;
const sc_lv<32> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv32_2 = "10";
const bool pooling2d_large_cl_nopad_pad_me_1::ap_const_boolean_0 = false;
const sc_lv<1> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv1_0 = "0";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv32_5 = "101";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv32_7 = "111";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv32_1 = "1";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv32_4 = "100";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv32_6 = "110";
const sc_lv<1> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv1_1 = "1";
const sc_lv<4> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv4_0 = "0000";
const sc_lv<8> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv8_0 = "00000000";
const sc_lv<5> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv5_0 = "00000";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv32_8 = "1000";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv32_3 = "11";
const sc_lv<4> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv4_8 = "1000";
const sc_lv<4> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv4_1 = "1";
const sc_lv<8> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv8_80 = "10000000";
const sc_lv<8> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv8_1 = "1";
const sc_lv<5> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv5_1 = "1";
const sc_lv<3> pooling2d_large_cl_nopad_pad_me_1::ap_const_lv3_0 = "000";

pooling2d_large_cl_nopad_pad_me_1::pooling2d_large_cl_nopad_pad_me_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    memory1_0_V_U = new pooling2d_large_cl_nopad_pad_me_1_memory1_0_V("memory1_0_V_U");
    memory1_0_V_U->clk(ap_clk);
    memory1_0_V_U->reset(ap_rst);
    memory1_0_V_U->address0(memory1_0_V_address0);
    memory1_0_V_U->ce0(memory1_0_V_ce0);
    memory1_0_V_U->we0(memory1_0_V_we0);
    memory1_0_V_U->d0(reg_234);
    memory1_0_V_U->q0(memory1_0_V_q0);
    memory1_1_V_U = new pooling2d_large_cl_nopad_pad_me_1_memory1_0_V("memory1_1_V_U");
    memory1_1_V_U->clk(ap_clk);
    memory1_1_V_U->reset(ap_rst);
    memory1_1_V_U->address0(memory1_1_V_address0);
    memory1_1_V_U->ce0(memory1_1_V_ce0);
    memory1_1_V_U->we0(memory1_1_V_we0);
    memory1_1_V_U->d0(reg_234);
    memory1_1_V_U->q0(memory1_1_V_q0);
    memory2_V_U = new pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config6jbC("memory2_V_U");
    memory2_V_U->clk(ap_clk);
    memory2_V_U->reset(ap_rst);
    memory2_V_U->address0(memory2_V_address0);
    memory2_V_U->ce0(memory2_V_ce0);
    memory2_V_U->we0(memory2_V_we0);
    memory2_V_U->d0(reg_234);
    memory2_V_U->q0(memory2_V_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln203_4_fu_395_p2);
    sensitive << ( zext_ln500_reg_507 );
    sensitive << ( zext_ln203_11_fu_391_p1 );

    SC_METHOD(thread_add_ln203_fu_327_p2);
    sensitive << ( zext_ln480_fu_320_p1 );
    sensitive << ( zext_ln203_fu_324_p1 );

    SC_METHOD(thread_add_ln479_fu_259_p2);
    sensitive << ( indvar_flatten_reg_165 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp2_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln479_reg_451 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln479_reg_451 );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln495_reg_498 );

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln495_reg_498 );

    SC_METHOD(thread_ap_block_pp2_stage0);

    SC_METHOD(thread_ap_block_pp2_stage0_01001);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter3_reg );
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter5_reg );

    SC_METHOD(thread_ap_block_pp2_stage0_11001);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter3_reg );
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter5_reg );

    SC_METHOD(thread_ap_block_pp2_stage0_subdone);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter3_reg );
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter5_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state10_pp1_stage0_iter2);

    SC_METHOD(thread_ap_block_state12_pp2_stage0_iter0);

    SC_METHOD(thread_ap_block_state13_pp2_stage0_iter1);

    SC_METHOD(thread_ap_block_state14_pp2_stage0_iter2);

    SC_METHOD(thread_ap_block_state15_pp2_stage0_iter3);

    SC_METHOD(thread_ap_block_state16_pp2_stage0_iter4);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( icmp_ln500_reg_512_pp2_iter3_reg );

    SC_METHOD(thread_ap_block_state17_pp2_stage0_iter5);

    SC_METHOD(thread_ap_block_state18_pp2_stage0_iter6);
    sensitive << ( res_V_V_full_n );
    sensitive << ( icmp_ln500_reg_512_pp2_iter5_reg );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( icmp_ln479_reg_451 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state8_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state9_pp1_stage0_iter1);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( icmp_ln495_reg_498 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( icmp_ln479_fu_253_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state8);
    sensitive << ( icmp_ln495_fu_350_p2 );

    SC_METHOD(thread_ap_condition_pp2_exit_iter0_state12);
    sensitive << ( icmp_ln500_fu_379_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( icmp_ln477_fu_241_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_enable_pp2);
    sensitive << ( ap_idle_pp2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter2 );

    SC_METHOD(thread_ap_idle_pp2);
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( ap_enable_reg_pp2_iter3 );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( ap_enable_reg_pp2_iter5 );

    SC_METHOD(thread_ap_phi_mux_j_0_phi_fu_180_p4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln479_reg_451 );
    sensitive << ( j_0_reg_176 );
    sensitive << ( select_ln203_4_reg_465 );

    SC_METHOD(thread_ap_phi_mux_k10_0_phi_fu_226_p4);
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( icmp_ln500_reg_512 );
    sensitive << ( k10_0_reg_222 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( k_8_reg_516 );
    sensitive << ( ap_enable_reg_pp2_iter1 );

    SC_METHOD(thread_ap_phi_mux_k9_0_phi_fu_214_p4);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( icmp_ln495_reg_498 );
    sensitive << ( k9_0_reg_210 );
    sensitive << ( k_7_reg_502 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_data_V_V_blk_n);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln479_reg_451 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( icmp_ln495_reg_498 );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter3_reg );

    SC_METHOD(thread_data_V_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln479_reg_451 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln495_reg_498 );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter3_reg );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_i_fu_247_p2);
    sensitive << ( i_0_reg_154 );

    SC_METHOD(thread_icmp_ln1494_1_fu_420_p2);
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter3_reg );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( pool_2_V_reg_553 );
    sensitive << ( select_ln510_reg_559 );

    SC_METHOD(thread_icmp_ln1494_2_fu_430_p2);
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( reg_234 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter4_reg );
    sensitive << ( select_ln510_5_reg_565 );
    sensitive << ( ap_enable_reg_pp2_iter5 );

    SC_METHOD(thread_icmp_ln1494_fu_410_p2);
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter2_reg );
    sensitive << ( max_V_reg_536 );
    sensitive << ( pool_1_V_reg_542 );
    sensitive << ( ap_enable_reg_pp2_iter3 );

    SC_METHOD(thread_icmp_ln477_fu_241_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_154 );

    SC_METHOD(thread_icmp_ln479_fu_253_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten_reg_165 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln480_fu_271_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( k_0_reg_187 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln479_fu_253_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln494_fu_338_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( j8_0_reg_198 );

    SC_METHOD(thread_icmp_ln495_fu_350_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_phi_mux_k9_0_phi_fu_214_p4 );

    SC_METHOD(thread_icmp_ln500_fu_379_p2);
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( ap_phi_mux_k10_0_phi_fu_226_p4 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( icmp_ln477_fu_241_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_j_26_fu_344_p2);
    sensitive << ( j8_0_reg_198 );

    SC_METHOD(thread_j_fu_265_p2);
    sensitive << ( ap_phi_mux_j_0_phi_fu_180_p4 );

    SC_METHOD(thread_k_7_fu_356_p2);
    sensitive << ( ap_phi_mux_k9_0_phi_fu_214_p4 );

    SC_METHOD(thread_k_8_fu_385_p2);
    sensitive << ( ap_phi_mux_k10_0_phi_fu_226_p4 );

    SC_METHOD(thread_k_fu_307_p2);
    sensitive << ( select_ln203_fu_277_p3 );

    SC_METHOD(thread_memory1_0_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( zext_ln203_10_fu_333_p1 );
    sensitive << ( zext_ln203_12_fu_400_p1 );

    SC_METHOD(thread_memory1_0_V_ce0);
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp2_iter1 );

    SC_METHOD(thread_memory1_0_V_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( trunc_ln203_reg_470_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_memory1_1_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( zext_ln203_10_fu_333_p1 );
    sensitive << ( zext_ln203_12_fu_400_p1 );

    SC_METHOD(thread_memory1_1_V_ce0);
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp2_iter1 );

    SC_METHOD(thread_memory1_1_V_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( trunc_ln203_reg_470_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_memory2_V_address0);
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( zext_ln498_fu_362_p1 );
    sensitive << ( zext_ln502_fu_405_p1 );

    SC_METHOD(thread_memory2_V_ce0);
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( ap_enable_reg_pp1_iter2 );

    SC_METHOD(thread_memory2_V_we0);
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( icmp_ln495_reg_498_pp1_iter1_reg );
    sensitive << ( ap_enable_reg_pp1_iter2 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_res_V_V_blk_n);
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter5_reg );

    SC_METHOD(thread_res_V_V_din);
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter5_reg );
    sensitive << ( tmp_V_reg_571 );
    sensitive << ( ap_block_pp2_stage0_01001 );

    SC_METHOD(thread_res_V_V_write);
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln500_reg_512_pp2_iter5_reg );
    sensitive << ( ap_block_pp2_stage0_11001 );

    SC_METHOD(thread_select_ln203_4_fu_285_p3);
    sensitive << ( ap_phi_mux_j_0_phi_fu_180_p4 );
    sensitive << ( icmp_ln480_fu_271_p2 );
    sensitive << ( j_fu_265_p2 );

    SC_METHOD(thread_select_ln203_fu_277_p3);
    sensitive << ( k_0_reg_187 );
    sensitive << ( icmp_ln480_fu_271_p2 );

    SC_METHOD(thread_select_ln510_5_fu_424_p3);
    sensitive << ( pool_2_V_reg_553 );
    sensitive << ( select_ln510_reg_559 );
    sensitive << ( icmp_ln1494_1_fu_420_p2 );

    SC_METHOD(thread_select_ln510_fu_414_p3);
    sensitive << ( max_V_reg_536 );
    sensitive << ( pool_1_V_reg_542 );
    sensitive << ( icmp_ln1494_fu_410_p2 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_7_fu_313_p3);
    sensitive << ( zext_ln203_mid2_v_reg_474 );

    SC_METHOD(thread_tmp_8_fu_367_p3);
    sensitive << ( j8_0_reg_198 );

    SC_METHOD(thread_tmp_V_fu_435_p3);
    sensitive << ( reg_234 );
    sensitive << ( select_ln510_5_reg_565 );
    sensitive << ( icmp_ln1494_2_fu_430_p2 );

    SC_METHOD(thread_trunc_ln203_fu_293_p1);
    sensitive << ( select_ln203_4_fu_285_p3 );

    SC_METHOD(thread_zext_ln203_10_fu_333_p1);
    sensitive << ( add_ln203_reg_484 );

    SC_METHOD(thread_zext_ln203_11_fu_391_p1);
    sensitive << ( ap_phi_mux_k10_0_phi_fu_226_p4 );

    SC_METHOD(thread_zext_ln203_12_fu_400_p1);
    sensitive << ( add_ln203_4_reg_521 );

    SC_METHOD(thread_zext_ln203_fu_324_p1);
    sensitive << ( select_ln203_reg_460 );

    SC_METHOD(thread_zext_ln480_fu_320_p1);
    sensitive << ( tmp_7_fu_313_p3 );

    SC_METHOD(thread_zext_ln498_fu_362_p1);
    sensitive << ( k9_0_reg_210_pp1_iter1_reg );

    SC_METHOD(thread_zext_ln500_fu_375_p1);
    sensitive << ( tmp_8_fu_367_p3 );

    SC_METHOD(thread_zext_ln502_fu_405_p1);
    sensitive << ( k10_0_reg_222_pp2_iter1_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp2_iter6 );
    sensitive << ( icmp_ln477_fu_241_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln479_fu_253_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln494_fu_338_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln495_fu_350_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( icmp_ln500_fu_379_p2 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_block_pp2_stage0_subdone );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( ap_enable_reg_pp2_iter5 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter5 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pooling2d_large_cl_nopad_pad_me_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, data_V_V_dout, "(port)data_V_V_dout");
    sc_trace(mVcdFile, data_V_V_empty_n, "(port)data_V_V_empty_n");
    sc_trace(mVcdFile, data_V_V_read, "(port)data_V_V_read");
    sc_trace(mVcdFile, res_V_V_din, "(port)res_V_V_din");
    sc_trace(mVcdFile, res_V_V_full_n, "(port)res_V_V_full_n");
    sc_trace(mVcdFile, res_V_V_write, "(port)res_V_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, data_V_V_blk_n, "data_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln479_reg_451, "icmp_ln479_reg_451");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, icmp_ln495_reg_498, "icmp_ln495_reg_498");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter4, "ap_enable_reg_pp2_iter4");
    sc_trace(mVcdFile, ap_block_pp2_stage0, "ap_block_pp2_stage0");
    sc_trace(mVcdFile, icmp_ln500_reg_512, "icmp_ln500_reg_512");
    sc_trace(mVcdFile, icmp_ln500_reg_512_pp2_iter3_reg, "icmp_ln500_reg_512_pp2_iter3_reg");
    sc_trace(mVcdFile, res_V_V_blk_n, "res_V_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter6, "ap_enable_reg_pp2_iter6");
    sc_trace(mVcdFile, icmp_ln500_reg_512_pp2_iter5_reg, "icmp_ln500_reg_512_pp2_iter5_reg");
    sc_trace(mVcdFile, indvar_flatten_reg_165, "indvar_flatten_reg_165");
    sc_trace(mVcdFile, j_0_reg_176, "j_0_reg_176");
    sc_trace(mVcdFile, k_0_reg_187, "k_0_reg_187");
    sc_trace(mVcdFile, k9_0_reg_210, "k9_0_reg_210");
    sc_trace(mVcdFile, k9_0_reg_210_pp1_iter1_reg, "k9_0_reg_210_pp1_iter1_reg");
    sc_trace(mVcdFile, ap_block_state8_pp1_stage0_iter0, "ap_block_state8_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state9_pp1_stage0_iter1, "ap_block_state9_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state10_pp1_stage0_iter2, "ap_block_state10_pp1_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, k10_0_reg_222, "k10_0_reg_222");
    sc_trace(mVcdFile, k10_0_reg_222_pp2_iter1_reg, "k10_0_reg_222_pp2_iter1_reg");
    sc_trace(mVcdFile, ap_CS_fsm_pp2_stage0, "ap_CS_fsm_pp2_stage0");
    sc_trace(mVcdFile, ap_block_state12_pp2_stage0_iter0, "ap_block_state12_pp2_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state13_pp2_stage0_iter1, "ap_block_state13_pp2_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state14_pp2_stage0_iter2, "ap_block_state14_pp2_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state15_pp2_stage0_iter3, "ap_block_state15_pp2_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state16_pp2_stage0_iter4, "ap_block_state16_pp2_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state17_pp2_stage0_iter5, "ap_block_state17_pp2_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state18_pp2_stage0_iter6, "ap_block_state18_pp2_stage0_iter6");
    sc_trace(mVcdFile, ap_block_pp2_stage0_11001, "ap_block_pp2_stage0_11001");
    sc_trace(mVcdFile, reg_234, "reg_234");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln477_fu_241_p2, "icmp_ln477_fu_241_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_247_p2, "i_fu_247_p2");
    sc_trace(mVcdFile, i_reg_446, "i_reg_446");
    sc_trace(mVcdFile, icmp_ln479_fu_253_p2, "icmp_ln479_fu_253_p2");
    sc_trace(mVcdFile, add_ln479_fu_259_p2, "add_ln479_fu_259_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, select_ln203_fu_277_p3, "select_ln203_fu_277_p3");
    sc_trace(mVcdFile, select_ln203_reg_460, "select_ln203_reg_460");
    sc_trace(mVcdFile, select_ln203_4_fu_285_p3, "select_ln203_4_fu_285_p3");
    sc_trace(mVcdFile, select_ln203_4_reg_465, "select_ln203_4_reg_465");
    sc_trace(mVcdFile, trunc_ln203_fu_293_p1, "trunc_ln203_fu_293_p1");
    sc_trace(mVcdFile, trunc_ln203_reg_470, "trunc_ln203_reg_470");
    sc_trace(mVcdFile, trunc_ln203_reg_470_pp0_iter1_reg, "trunc_ln203_reg_470_pp0_iter1_reg");
    sc_trace(mVcdFile, zext_ln203_mid2_v_reg_474, "zext_ln203_mid2_v_reg_474");
    sc_trace(mVcdFile, k_fu_307_p2, "k_fu_307_p2");
    sc_trace(mVcdFile, add_ln203_fu_327_p2, "add_ln203_fu_327_p2");
    sc_trace(mVcdFile, add_ln203_reg_484, "add_ln203_reg_484");
    sc_trace(mVcdFile, icmp_ln494_fu_338_p2, "icmp_ln494_fu_338_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, j_26_fu_344_p2, "j_26_fu_344_p2");
    sc_trace(mVcdFile, j_26_reg_493, "j_26_reg_493");
    sc_trace(mVcdFile, icmp_ln495_fu_350_p2, "icmp_ln495_fu_350_p2");
    sc_trace(mVcdFile, icmp_ln495_reg_498_pp1_iter1_reg, "icmp_ln495_reg_498_pp1_iter1_reg");
    sc_trace(mVcdFile, k_7_fu_356_p2, "k_7_fu_356_p2");
    sc_trace(mVcdFile, k_7_reg_502, "k_7_reg_502");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, zext_ln500_fu_375_p1, "zext_ln500_fu_375_p1");
    sc_trace(mVcdFile, zext_ln500_reg_507, "zext_ln500_reg_507");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, icmp_ln500_fu_379_p2, "icmp_ln500_fu_379_p2");
    sc_trace(mVcdFile, icmp_ln500_reg_512_pp2_iter1_reg, "icmp_ln500_reg_512_pp2_iter1_reg");
    sc_trace(mVcdFile, icmp_ln500_reg_512_pp2_iter2_reg, "icmp_ln500_reg_512_pp2_iter2_reg");
    sc_trace(mVcdFile, icmp_ln500_reg_512_pp2_iter4_reg, "icmp_ln500_reg_512_pp2_iter4_reg");
    sc_trace(mVcdFile, k_8_fu_385_p2, "k_8_fu_385_p2");
    sc_trace(mVcdFile, k_8_reg_516, "k_8_reg_516");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter0, "ap_enable_reg_pp2_iter0");
    sc_trace(mVcdFile, add_ln203_4_fu_395_p2, "add_ln203_4_fu_395_p2");
    sc_trace(mVcdFile, add_ln203_4_reg_521, "add_ln203_4_reg_521");
    sc_trace(mVcdFile, memory1_0_V_q0, "memory1_0_V_q0");
    sc_trace(mVcdFile, max_V_reg_536, "max_V_reg_536");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter2, "ap_enable_reg_pp2_iter2");
    sc_trace(mVcdFile, memory1_1_V_q0, "memory1_1_V_q0");
    sc_trace(mVcdFile, pool_1_V_reg_542, "pool_1_V_reg_542");
    sc_trace(mVcdFile, memory2_V_q0, "memory2_V_q0");
    sc_trace(mVcdFile, pool_2_V_reg_553, "pool_2_V_reg_553");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter3, "ap_enable_reg_pp2_iter3");
    sc_trace(mVcdFile, select_ln510_fu_414_p3, "select_ln510_fu_414_p3");
    sc_trace(mVcdFile, select_ln510_reg_559, "select_ln510_reg_559");
    sc_trace(mVcdFile, select_ln510_5_fu_424_p3, "select_ln510_5_fu_424_p3");
    sc_trace(mVcdFile, select_ln510_5_reg_565, "select_ln510_5_reg_565");
    sc_trace(mVcdFile, tmp_V_fu_435_p3, "tmp_V_fu_435_p3");
    sc_trace(mVcdFile, tmp_V_reg_571, "tmp_V_reg_571");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state8, "ap_condition_pp1_exit_iter0_state8");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter2, "ap_enable_reg_pp1_iter2");
    sc_trace(mVcdFile, ap_block_pp2_stage0_subdone, "ap_block_pp2_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp2_exit_iter0_state12, "ap_condition_pp2_exit_iter0_state12");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter1, "ap_enable_reg_pp2_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter5, "ap_enable_reg_pp2_iter5");
    sc_trace(mVcdFile, memory1_0_V_address0, "memory1_0_V_address0");
    sc_trace(mVcdFile, memory1_0_V_ce0, "memory1_0_V_ce0");
    sc_trace(mVcdFile, memory1_0_V_we0, "memory1_0_V_we0");
    sc_trace(mVcdFile, memory1_1_V_address0, "memory1_1_V_address0");
    sc_trace(mVcdFile, memory1_1_V_ce0, "memory1_1_V_ce0");
    sc_trace(mVcdFile, memory1_1_V_we0, "memory1_1_V_we0");
    sc_trace(mVcdFile, memory2_V_address0, "memory2_V_address0");
    sc_trace(mVcdFile, memory2_V_ce0, "memory2_V_ce0");
    sc_trace(mVcdFile, memory2_V_we0, "memory2_V_we0");
    sc_trace(mVcdFile, i_0_reg_154, "i_0_reg_154");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_phi_mux_j_0_phi_fu_180_p4, "ap_phi_mux_j_0_phi_fu_180_p4");
    sc_trace(mVcdFile, j8_0_reg_198, "j8_0_reg_198");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_phi_mux_k9_0_phi_fu_214_p4, "ap_phi_mux_k9_0_phi_fu_214_p4");
    sc_trace(mVcdFile, ap_phi_mux_k10_0_phi_fu_226_p4, "ap_phi_mux_k10_0_phi_fu_226_p4");
    sc_trace(mVcdFile, zext_ln203_10_fu_333_p1, "zext_ln203_10_fu_333_p1");
    sc_trace(mVcdFile, zext_ln498_fu_362_p1, "zext_ln498_fu_362_p1");
    sc_trace(mVcdFile, zext_ln203_12_fu_400_p1, "zext_ln203_12_fu_400_p1");
    sc_trace(mVcdFile, zext_ln502_fu_405_p1, "zext_ln502_fu_405_p1");
    sc_trace(mVcdFile, ap_block_pp2_stage0_01001, "ap_block_pp2_stage0_01001");
    sc_trace(mVcdFile, icmp_ln480_fu_271_p2, "icmp_ln480_fu_271_p2");
    sc_trace(mVcdFile, j_fu_265_p2, "j_fu_265_p2");
    sc_trace(mVcdFile, tmp_7_fu_313_p3, "tmp_7_fu_313_p3");
    sc_trace(mVcdFile, zext_ln480_fu_320_p1, "zext_ln480_fu_320_p1");
    sc_trace(mVcdFile, zext_ln203_fu_324_p1, "zext_ln203_fu_324_p1");
    sc_trace(mVcdFile, tmp_8_fu_367_p3, "tmp_8_fu_367_p3");
    sc_trace(mVcdFile, zext_ln203_11_fu_391_p1, "zext_ln203_11_fu_391_p1");
    sc_trace(mVcdFile, icmp_ln1494_fu_410_p2, "icmp_ln1494_fu_410_p2");
    sc_trace(mVcdFile, icmp_ln1494_1_fu_420_p2, "icmp_ln1494_1_fu_420_p2");
    sc_trace(mVcdFile, icmp_ln1494_2_fu_430_p2, "icmp_ln1494_2_fu_430_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
    sc_trace(mVcdFile, ap_idle_pp2, "ap_idle_pp2");
    sc_trace(mVcdFile, ap_enable_pp2, "ap_enable_pp2");
#endif

    }
}

pooling2d_large_cl_nopad_pad_me_1::~pooling2d_large_cl_nopad_pad_me_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete memory1_0_V_U;
    delete memory1_1_V_U;
    delete memory2_V_U;
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(icmp_ln477_fu_241_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln477_fu_241_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln477_fu_241_p2.read()))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state8.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln494_fu_338_p2.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state8.read())) {
                ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state8.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter2 = ap_enable_reg_pp1_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln494_fu_338_p2.read()))) {
            ap_enable_reg_pp1_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp2_exit_iter0_state12.read()))) {
            ap_enable_reg_pp2_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
            ap_enable_reg_pp2_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp2_exit_iter0_state12.read())) {
                ap_enable_reg_pp2_iter1 = (ap_condition_pp2_exit_iter0_state12.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp2_iter1 = ap_enable_reg_pp2_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter2 = ap_enable_reg_pp2_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter3 = ap_enable_reg_pp2_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter4 = ap_enable_reg_pp2_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter5 = ap_enable_reg_pp2_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter6 = ap_enable_reg_pp2_iter5.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
            ap_enable_reg_pp2_iter6 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(icmp_ln494_fu_338_p2.read(), ap_const_lv1_1))) {
        i_0_reg_154 = i_reg_446.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_0_reg_154 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln477_fu_241_p2.read()))) {
        indvar_flatten_reg_165 = ap_const_lv8_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln479_fu_253_p2.read()))) {
        indvar_flatten_reg_165 = add_ln479_fu_259_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j8_0_reg_198 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        j8_0_reg_198 = j_26_reg_493.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln477_fu_241_p2.read()))) {
        j_0_reg_176 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(icmp_ln479_reg_451.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        j_0_reg_176 = select_ln203_4_reg_465.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        k10_0_reg_222 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        k10_0_reg_222 = k_8_reg_516.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln494_fu_338_p2.read()))) {
        k9_0_reg_210 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_498.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        k9_0_reg_210 = k_7_reg_502.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln477_fu_241_p2.read()))) {
        k_0_reg_187 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln479_fu_253_p2.read()))) {
        k_0_reg_187 = k_fu_307_p2.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_fu_379_p2.read()))) {
        add_ln203_4_reg_521 = add_ln203_4_fu_395_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(icmp_ln479_reg_451.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        add_ln203_reg_484 = add_ln203_fu_327_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_446 = i_fu_247_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln479_reg_451 = icmp_ln479_fu_253_p2.read();
        trunc_ln203_reg_470_pp0_iter1_reg = trunc_ln203_reg_470.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln495_reg_498 = icmp_ln495_fu_350_p2.read();
        icmp_ln495_reg_498_pp1_iter1_reg = icmp_ln495_reg_498.read();
        k9_0_reg_210_pp1_iter1_reg = k9_0_reg_210.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln500_reg_512 = icmp_ln500_fu_379_p2.read();
        icmp_ln500_reg_512_pp2_iter1_reg = icmp_ln500_reg_512.read();
        k10_0_reg_222_pp2_iter1_reg = k10_0_reg_222.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln500_reg_512_pp2_iter2_reg = icmp_ln500_reg_512_pp2_iter1_reg.read();
        icmp_ln500_reg_512_pp2_iter3_reg = icmp_ln500_reg_512_pp2_iter2_reg.read();
        icmp_ln500_reg_512_pp2_iter4_reg = icmp_ln500_reg_512_pp2_iter3_reg.read();
        icmp_ln500_reg_512_pp2_iter5_reg = icmp_ln500_reg_512_pp2_iter4_reg.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        j_26_reg_493 = j_26_fu_344_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        k_7_reg_502 = k_7_fu_356_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()))) {
        k_8_reg_516 = k_8_fu_385_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter1_reg.read()))) {
        max_V_reg_536 = memory1_0_V_q0.read();
        pool_1_V_reg_542 = memory1_1_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter2_reg.read()))) {
        pool_2_V_reg_553 = memory2_V_q0.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln479_reg_451.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_498.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0)))) {
        reg_234 = data_V_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln479_fu_253_p2.read()))) {
        select_ln203_4_reg_465 = select_ln203_4_fu_285_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln479_fu_253_p2.read()))) {
        select_ln203_reg_460 = select_ln203_fu_277_p3.read();
        trunc_ln203_reg_470 = trunc_ln203_fu_293_p1.read();
        zext_ln203_mid2_v_reg_474 = select_ln203_4_fu_285_p3.read().range(4, 1);
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter3_reg.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0))) {
        select_ln510_5_reg_565 = select_ln510_5_fu_424_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter2_reg.read()))) {
        select_ln510_reg_559 = select_ln510_fu_414_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter4_reg.read()))) {
        tmp_V_reg_571 = tmp_V_fu_435_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        zext_ln500_reg_507 = zext_ln500_fu_375_p1.read();
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_add_ln203_4_fu_395_p2() {
    add_ln203_4_fu_395_p2 = (!zext_ln500_reg_507.read().is_01() || !zext_ln203_11_fu_391_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln500_reg_507.read()) + sc_biguint<8>(zext_ln203_11_fu_391_p1.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_add_ln203_fu_327_p2() {
    add_ln203_fu_327_p2 = (!zext_ln480_fu_320_p1.read().is_01() || !zext_ln203_fu_324_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln480_fu_320_p1.read()) + sc_biguint<8>(zext_ln203_fu_324_p1.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_add_ln479_fu_259_p2() {
    add_ln479_fu_259_p2 = (!indvar_flatten_reg_165.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(indvar_flatten_reg_165.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[5];
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_CS_fsm_pp2_stage0() {
    ap_CS_fsm_pp2_stage0 = ap_CS_fsm.read()[7];
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[6];
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[8];
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[3];
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[4];
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(icmp_ln479_reg_451.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(icmp_ln479_reg_451.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_498.read()) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_498.read()) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_pp2_stage0() {
    ap_block_pp2_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_pp2_stage0_01001() {
    ap_block_pp2_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter5_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read())));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_pp2_stage0_11001() {
    ap_block_pp2_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter5_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read())));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_pp2_stage0_subdone() {
    ap_block_pp2_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter5_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read())));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state10_pp1_stage0_iter2() {
    ap_block_state10_pp1_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state12_pp2_stage0_iter0() {
    ap_block_state12_pp2_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state13_pp2_stage0_iter1() {
    ap_block_state13_pp2_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state14_pp2_stage0_iter2() {
    ap_block_state14_pp2_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state15_pp2_stage0_iter3() {
    ap_block_state15_pp2_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state16_pp2_stage0_iter4() {
    ap_block_state16_pp2_stage0_iter4 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter3_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state17_pp2_stage0_iter5() {
    ap_block_state17_pp2_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state18_pp2_stage0_iter6() {
    ap_block_state18_pp2_stage0_iter6 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter5_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(icmp_ln479_reg_451.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state8_pp1_stage0_iter0() {
    ap_block_state8_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_block_state9_pp1_stage0_iter1() {
    ap_block_state9_pp1_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_498.read()) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(icmp_ln479_fu_253_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_condition_pp1_exit_iter0_state8() {
    if (esl_seteq<1,1,1>(icmp_ln495_fu_350_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp1_exit_iter0_state8 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state8 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_condition_pp2_exit_iter0_state12() {
    if (esl_seteq<1,1,1>(icmp_ln500_fu_379_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp2_exit_iter0_state12 = ap_const_logic_1;
    } else {
        ap_condition_pp2_exit_iter0_state12 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln477_fu_241_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_enable_pp2() {
    ap_enable_pp2 = (ap_idle_pp2.read() ^ ap_const_logic_1);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter2.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_idle_pp2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter6.read()))) {
        ap_idle_pp2 = ap_const_logic_1;
    } else {
        ap_idle_pp2 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_phi_mux_j_0_phi_fu_180_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln479_reg_451.read(), ap_const_lv1_0))) {
        ap_phi_mux_j_0_phi_fu_180_p4 = select_ln203_4_reg_465.read();
    } else {
        ap_phi_mux_j_0_phi_fu_180_p4 = j_0_reg_176.read();
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_phi_mux_k10_0_phi_fu_226_p4() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        ap_phi_mux_k10_0_phi_fu_226_p4 = k_8_reg_516.read();
    } else {
        ap_phi_mux_k10_0_phi_fu_226_p4 = k10_0_reg_222.read();
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_phi_mux_k9_0_phi_fu_214_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_498.read()))) {
        ap_phi_mux_k9_0_phi_fu_214_p4 = k_7_reg_502.read();
    } else {
        ap_phi_mux_k9_0_phi_fu_214_p4 = k9_0_reg_210.read();
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void pooling2d_large_cl_nopad_pad_me_1::thread_data_V_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln479_reg_451.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_498.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter3_reg.read())))) {
        data_V_V_blk_n = data_V_V_empty_n.read();
    } else {
        data_V_V_blk_n = ap_const_logic_1;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_data_V_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(icmp_ln479_reg_451.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_498.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter3_reg.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0)))) {
        data_V_V_read = ap_const_logic_1;
    } else {
        data_V_V_read = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_i_fu_247_p2() {
    i_fu_247_p2 = (!i_0_reg_154.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_154.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_icmp_ln1494_1_fu_420_p2() {
    icmp_ln1494_1_fu_420_p2 = (!pool_2_V_reg_553.read().is_01() || !select_ln510_reg_559.read().is_01())? sc_lv<1>(): (sc_bigint<32>(pool_2_V_reg_553.read()) > sc_bigint<32>(select_ln510_reg_559.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_icmp_ln1494_2_fu_430_p2() {
    icmp_ln1494_2_fu_430_p2 = (!reg_234.read().is_01() || !select_ln510_5_reg_565.read().is_01())? sc_lv<1>(): (sc_bigint<32>(reg_234.read()) > sc_bigint<32>(select_ln510_5_reg_565.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_icmp_ln1494_fu_410_p2() {
    icmp_ln1494_fu_410_p2 = (!pool_1_V_reg_542.read().is_01() || !max_V_reg_536.read().is_01())? sc_lv<1>(): (sc_bigint<32>(pool_1_V_reg_542.read()) > sc_bigint<32>(max_V_reg_536.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_icmp_ln477_fu_241_p2() {
    icmp_ln477_fu_241_p2 = (!i_0_reg_154.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_154.read() == ap_const_lv4_8);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_icmp_ln479_fu_253_p2() {
    icmp_ln479_fu_253_p2 = (!indvar_flatten_reg_165.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_165.read() == ap_const_lv8_80);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_icmp_ln480_fu_271_p2() {
    icmp_ln480_fu_271_p2 = (!k_0_reg_187.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_187.read() == ap_const_lv4_8);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_icmp_ln494_fu_338_p2() {
    icmp_ln494_fu_338_p2 = (!j8_0_reg_198.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(j8_0_reg_198.read() == ap_const_lv4_8);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_icmp_ln495_fu_350_p2() {
    icmp_ln495_fu_350_p2 = (!ap_phi_mux_k9_0_phi_fu_214_p4.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_k9_0_phi_fu_214_p4.read() == ap_const_lv4_8);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_icmp_ln500_fu_379_p2() {
    icmp_ln500_fu_379_p2 = (!ap_phi_mux_k10_0_phi_fu_226_p4.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_k10_0_phi_fu_226_p4.read() == ap_const_lv4_8);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln477_fu_241_p2.read(), ap_const_lv1_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_j_26_fu_344_p2() {
    j_26_fu_344_p2 = (!j8_0_reg_198.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j8_0_reg_198.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_j_fu_265_p2() {
    j_fu_265_p2 = (!ap_const_lv5_1.is_01() || !ap_phi_mux_j_0_phi_fu_180_p4.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_1) + sc_biguint<5>(ap_phi_mux_j_0_phi_fu_180_p4.read()));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_k_7_fu_356_p2() {
    k_7_fu_356_p2 = (!ap_phi_mux_k9_0_phi_fu_214_p4.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(ap_phi_mux_k9_0_phi_fu_214_p4.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_k_8_fu_385_p2() {
    k_8_fu_385_p2 = (!ap_phi_mux_k10_0_phi_fu_226_p4.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(ap_phi_mux_k10_0_phi_fu_226_p4.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_k_fu_307_p2() {
    k_fu_307_p2 = (!select_ln203_fu_277_p3.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(select_ln203_fu_277_p3.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void pooling2d_large_cl_nopad_pad_me_1::thread_memory1_0_V_address0() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        memory1_0_V_address0 =  (sc_lv<6>) (zext_ln203_12_fu_400_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        memory1_0_V_address0 =  (sc_lv<6>) (zext_ln203_10_fu_333_p1.read());
    } else {
        memory1_0_V_address0 = "XXXXXX";
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_memory1_0_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())))) {
        memory1_0_V_ce0 = ap_const_logic_1;
    } else {
        memory1_0_V_ce0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_memory1_0_V_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln203_reg_470_pp0_iter1_reg.read()))) {
        memory1_0_V_we0 = ap_const_logic_1;
    } else {
        memory1_0_V_we0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_memory1_1_V_address0() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        memory1_1_V_address0 =  (sc_lv<6>) (zext_ln203_12_fu_400_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        memory1_1_V_address0 =  (sc_lv<6>) (zext_ln203_10_fu_333_p1.read());
    } else {
        memory1_1_V_address0 = "XXXXXX";
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_memory1_1_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())))) {
        memory1_1_V_ce0 = ap_const_logic_1;
    } else {
        memory1_1_V_ce0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_memory1_1_V_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(trunc_ln203_reg_470_pp0_iter1_reg.read(), ap_const_lv1_1))) {
        memory1_1_V_we0 = ap_const_logic_1;
    } else {
        memory1_1_V_we0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_memory2_V_address0() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()))) {
        memory2_V_address0 =  (sc_lv<3>) (zext_ln502_fu_405_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()))) {
        memory2_V_address0 =  (sc_lv<3>) (zext_ln498_fu_362_p1.read());
    } else {
        memory2_V_address0 =  (sc_lv<3>) ("XXX");
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_memory2_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read())))) {
        memory2_V_ce0 = ap_const_logic_1;
    } else {
        memory2_V_ce0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_memory2_V_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln495_reg_498_pp1_iter1_reg.read()))) {
        memory2_V_we0 = ap_const_logic_1;
    } else {
        memory2_V_we0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_res_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter5_reg.read()))) {
        res_V_V_blk_n = res_V_V_full_n.read();
    } else {
        res_V_V_blk_n = ap_const_logic_1;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_res_V_V_din() {
    res_V_V_din = tmp_V_reg_571.read();
}

void pooling2d_large_cl_nopad_pad_me_1::thread_res_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_reg_512_pp2_iter5_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_V_write = ap_const_logic_1;
    } else {
        res_V_V_write = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_select_ln203_4_fu_285_p3() {
    select_ln203_4_fu_285_p3 = (!icmp_ln480_fu_271_p2.read()[0].is_01())? sc_lv<5>(): ((icmp_ln480_fu_271_p2.read()[0].to_bool())? j_fu_265_p2.read(): ap_phi_mux_j_0_phi_fu_180_p4.read());
}

void pooling2d_large_cl_nopad_pad_me_1::thread_select_ln203_fu_277_p3() {
    select_ln203_fu_277_p3 = (!icmp_ln480_fu_271_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln480_fu_271_p2.read()[0].to_bool())? ap_const_lv4_0: k_0_reg_187.read());
}

void pooling2d_large_cl_nopad_pad_me_1::thread_select_ln510_5_fu_424_p3() {
    select_ln510_5_fu_424_p3 = (!icmp_ln1494_1_fu_420_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln1494_1_fu_420_p2.read()[0].to_bool())? pool_2_V_reg_553.read(): select_ln510_reg_559.read());
}

void pooling2d_large_cl_nopad_pad_me_1::thread_select_ln510_fu_414_p3() {
    select_ln510_fu_414_p3 = (!icmp_ln1494_fu_410_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln1494_fu_410_p2.read()[0].to_bool())? pool_1_V_reg_542.read(): max_V_reg_536.read());
}

void pooling2d_large_cl_nopad_pad_me_1::thread_start_out() {
    start_out = real_start.read();
}

void pooling2d_large_cl_nopad_pad_me_1::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me_1::thread_tmp_7_fu_313_p3() {
    tmp_7_fu_313_p3 = esl_concat<4,3>(zext_ln203_mid2_v_reg_474.read(), ap_const_lv3_0);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_tmp_8_fu_367_p3() {
    tmp_8_fu_367_p3 = esl_concat<4,3>(j8_0_reg_198.read(), ap_const_lv3_0);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_tmp_V_fu_435_p3() {
    tmp_V_fu_435_p3 = (!icmp_ln1494_2_fu_430_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln1494_2_fu_430_p2.read()[0].to_bool())? reg_234.read(): select_ln510_5_reg_565.read());
}

void pooling2d_large_cl_nopad_pad_me_1::thread_trunc_ln203_fu_293_p1() {
    trunc_ln203_fu_293_p1 = select_ln203_4_fu_285_p3.read().range(1-1, 0);
}

void pooling2d_large_cl_nopad_pad_me_1::thread_zext_ln203_10_fu_333_p1() {
    zext_ln203_10_fu_333_p1 = esl_zext<64,8>(add_ln203_reg_484.read());
}

void pooling2d_large_cl_nopad_pad_me_1::thread_zext_ln203_11_fu_391_p1() {
    zext_ln203_11_fu_391_p1 = esl_zext<8,4>(ap_phi_mux_k10_0_phi_fu_226_p4.read());
}

void pooling2d_large_cl_nopad_pad_me_1::thread_zext_ln203_12_fu_400_p1() {
    zext_ln203_12_fu_400_p1 = esl_zext<64,8>(add_ln203_4_reg_521.read());
}

void pooling2d_large_cl_nopad_pad_me_1::thread_zext_ln203_fu_324_p1() {
    zext_ln203_fu_324_p1 = esl_zext<8,4>(select_ln203_reg_460.read());
}

void pooling2d_large_cl_nopad_pad_me_1::thread_zext_ln480_fu_320_p1() {
    zext_ln480_fu_320_p1 = esl_zext<8,7>(tmp_7_fu_313_p3.read());
}

void pooling2d_large_cl_nopad_pad_me_1::thread_zext_ln498_fu_362_p1() {
    zext_ln498_fu_362_p1 = esl_zext<64,4>(k9_0_reg_210_pp1_iter1_reg.read());
}

void pooling2d_large_cl_nopad_pad_me_1::thread_zext_ln500_fu_375_p1() {
    zext_ln500_fu_375_p1 = esl_zext<8,7>(tmp_8_fu_367_p3.read());
}

void pooling2d_large_cl_nopad_pad_me_1::thread_zext_ln502_fu_405_p1() {
    zext_ln502_fu_405_p1 = esl_zext<64,4>(k10_0_reg_222_pp2_iter1_reg.read());
}

void pooling2d_large_cl_nopad_pad_me_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln477_fu_241_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln479_fu_253_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln479_fu_253_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln494_fu_338_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 32 : 
            if ((!(esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln495_fu_350_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if (((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln495_fu_350_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            break;
        case 128 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp2_iter5.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln500_fu_379_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp2_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter6.read()) && 
  esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp2_iter5.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln500_fu_379_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp2_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

