// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _product_dense_ap_fixed_ap_fixed_ap_fixed_s_HH_
#define _product_dense_ap_fixed_ap_fixed_ap_fixed_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "myproject_axi_mul_32s_15s_47_5_1.h"

namespace ap_rtl {

struct product_dense_ap_fixed_ap_fixed_ap_fixed_s : public sc_module {
    // Port declarations 5
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<32> > a_V;
    sc_in< sc_lv<15> > w_V;
    sc_out< sc_lv<31> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    product_dense_ap_fixed_ap_fixed_ap_fixed_s(sc_module_name name);
    SC_HAS_PROCESS(product_dense_ap_fixed_ap_fixed_ap_fixed_s);

    ~product_dense_ap_fixed_ap_fixed_ap_fixed_s();

    sc_trace_file* mVcdFile;

    myproject_axi_mul_32s_15s_47_5_1<1,5,32,15,47>* myproject_axi_mul_32s_15s_47_5_1_U17;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<47> > grp_fu_34_p2;
    sc_signal< sc_lv<32> > a_V_int_reg;
    sc_signal< sc_lv<15> > w_V_int_reg;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_2E;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_block_state3_pp0_stage0_iter2();
    void thread_ap_block_state4_pp0_stage0_iter3();
    void thread_ap_block_state5_pp0_stage0_iter4();
    void thread_ap_return();
};

}

using namespace ap_rtl;

#endif
